#import "PVPDFSource.h"
#import "PVRenderProtocol.h"
#include <sys/mman.h>
#include <sys/stat.h>
#include <sys/mount.h>
#include <sys/file.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <mach/mach_time.h>
#include <poll.h>
#include <fcntl.h>
#include <unistd.h>
#include <signal.h>
#include <spawn.h>
#include <errno.h>

// Deliberately no PVRenderCore.h and no <CoreGraphics/CGPDFDocument.h> use.
// This process does not open PDFs. See PVPDFSource.h.

// The largest source document this viewer will copy, and the free space it
// insists on having left over afterwards.
//
// Neither bound existed, and the copy loop below reads until EOF. A sparse
// regular file is the cheap way to demonstrate the problem -- a hundred
// gigabytes of holes costs nothing to create and fills the boot volume when
// copied -- but any large regular file does it, and the temporary directory
// filling up takes the rest of the system with it, not just Postview. Two
// gigabytes is far past any PDF that can be presented on the target hardware.
#define PV_MAX_PDF_BYTES     (2LL * 1024LL * 1024LL * 1024LL)
#define PV_SNAPSHOT_HEADROOM (256LL * 1024LL * 1024LL)

// Renders one helper serves before it is retired and replaced.
//
// Quartz accumulates parsed content inside a CGPDFDocumentRef -- fonts, shading
// dictionaries, decoded images -- and never gives it back while the document is
// open. Measured at 183-242 MB of helper RSS against 34-40 MB in the viewer,
// which the soak gate could not see because it only ever looked at
// mach_task_self(). The process boundary that contains the faults is also the
// only lever that reclaims this: a fresh helper starts at nothing.
//
// Retired between renders, chosen by the viewer, so a recycle never turns into
// a failed page. A frame this large is worth recycling for on its own: it is a
// zoomed page whose parse cost is already paid and whose peak is the thing the
// budget cannot absorb twice.
#define PV_HELPER_MAX_RENDERS  128
#define PV_HELPER_LARGE_FRAME  (64ULL * 1024ULL * 1024ULL)

static NSError *PVError(NSInteger code, NSString *desc, NSString *reason)
{
    NSMutableDictionary *info = [NSMutableDictionary dictionary];
    if (desc)   [info setObject:desc   forKey:NSLocalizedDescriptionKey];
    if (reason) [info setObject:reason forKey:NSLocalizedRecoverySuggestionErrorKey];
    return [NSError errorWithDomain:@"PostviewErrorDomain" code:code userInfo:info];
}

// The largest page dimension the layout maths is willing to carry, in points.
// The PDF format's own limit is 14400 pt (200 in); anything past this is either
// corrupt or generated by something that did not read the spec.
#define PV_MAX_PAGE_POINTS  20000.0

// The longest name shm_open will accept, including the leading slash.
//
// This is PSHMNAMLEN, and it is 31 -- not PATH_MAX, and not the 96-byte field
// the protocol carries the name in. A longer name is refused outright with
// ENAMETOOLONG, so a naming scheme that grows with a counter stops working
// partway through a session rather than never working: measured, the previous
// scheme ("/postview-<pid>-<pointer>-<counter>") fitted for the first 99
// renders of a source and failed for every render after that, permanently,
// with the pages simply staying blank.
#define PV_SHM_NAME_MAX 31

// A page size layout can work with, preserving the page's shape.
//
// The two axes are clamped TOGETHER. They used to be clamped independently --
// each axis that was degenerate or past the ceiling was replaced with the
// corresponding US Letter dimension -- and for a page that failed on one axis
// only, that invents an aspect ratio the document does not have. A 25000 x 300
// pt banner became a 612 x 300 pt page: the renderer then fits the real crop
// box into that frame, which preserves aspect and so draws the banner as a
// 612 x 7 pt strip marooned in a 612 x 300 pt page, with the rest of the frame
// blank. The page is not distorted but it is the wrong page, and nothing
// anywhere says so.
//
// Scaling both axes by one factor keeps the shape, so the oversized page is
// simply presented smaller -- which is what a viewer should do with a page too
// large to lay out. Only a size that is degenerate in a way no scale can fix
// (non-finite, or not positive on both axes) falls back to US Letter, and that
// is a page with no geometry rather than one with too much.
static CGSize PVUsablePageSize(CGSize s)
{
    if (!isfinite(s.width) || !isfinite(s.height) ||
        !(s.width > 1) || !(s.height > 1))
        return CGSizeMake(612, 792);

    double k = 1.0;
    if (s.width  > PV_MAX_PAGE_POINTS) k = PV_MAX_PAGE_POINTS / (double)s.width;
    if (s.height > PV_MAX_PAGE_POINTS) {
        double kh = PV_MAX_PAGE_POINTS / (double)s.height;
        if (kh < k) k = kh;
    }
    if (k >= 1.0) return s;

    CGSize out = CGSizeMake((CGFloat)((double)s.width * k),
                            (CGFloat)((double)s.height * k));
    // The scale cannot make either axis degenerate -- both were above 1 and the
    // factor is the ratio of the ceiling to the larger of them -- but the floor
    // is stated rather than reasoned about, because everything downstream
    // divides by these.
    if (!(out.width  > 1) || !isfinite(out.width))  out.width  = 1;
    if (!(out.height > 1) || !isfinite(out.height)) out.height = 1;
    return out;
}

@interface PVPDFSnapshot : NSObject {
    NSString *_path;
    // Held open for the snapshot's whole life, carrying a shared advisory lock
    // and nothing else. It is never read or written through. See
    // PVSweepAbandonedSnapshots.
    int       _lockFD;
}
- (id)initWithSourceURL:(NSURL *)url error:(NSError **)outError;
- (NSString *)path;
@end

// The prefix every snapshot's name begins with. One definition, because a
// sweeper that disagreed with the maker about the name would either delete
// nothing or delete something else.
#define PV_SNAPSHOT_PREFIX "Postview-PDF-"

// Snapshots left behind by processes that are gone.
//
// A snapshot is unlinked in -dealloc, which covers every ordinary exit and none
// of the others: kill -9, a crash, a power cut. Measured on the development
// machine after a day of testing -- 41 abandoned files, ~100 MB. The system
// does eventually reap its temporary directory, but "eventually" is not a
// bound, and a reader who crashes twice a week accumulates.
//
// Whether a file is abandoned is asked, not guessed. Every live snapshot holds
// a shared advisory lock on its own file for as long as it exists, so a file
// that will accept an exclusive lock is a file no live snapshot is using. That
// is exact, unlike an age heuristic, which would eventually delete the snapshot
// of a document somebody has had open all week.
//
// The age test is kept as well, and only as a courtesy to a DIFFERENT build:
// a Postview old enough not to take the lock would otherwise have its snapshot
// swept while it was still reading it. An hour is far longer than the window
// between making a snapshot and opening it.
#define PV_SNAPSHOT_STALE_SECONDS (3600.0)

static void PVSweepAbandonedSnapshots(void)
{
    NSString *directory = NSTemporaryDirectory();
    if (![directory length]) return;

    NSFileManager *fm = [NSFileManager defaultManager];
    NSArray *names = [fm contentsOfDirectoryAtPath:directory error:NULL];
    NSString *prefix = [NSString stringWithUTF8String:PV_SNAPSHOT_PREFIX];
    NSUInteger i, n = [names count];
    for (i = 0; i < n; i++) {
        NSString *name = [names objectAtIndex:i];
        if (![name isKindOfClass:[NSString class]]) continue;
        if (![name hasPrefix:prefix]) continue;

        NSString *path = [directory stringByAppendingPathComponent:name];
        const char *fsPath = [path fileSystemRepresentation];
        int fd = open(fsPath, O_RDONLY);
        if (fd < 0) continue;

        struct stat info;
        BOOL old = (fstat(fd, &info) == 0 && S_ISREG(info.st_mode) &&
                    (time(NULL) - info.st_mtimespec.tv_sec) >
                        (time_t)PV_SNAPSHOT_STALE_SECONDS);
        // The exclusive lock is the question and the answer both: taking it
        // proves nothing else holds it, and holding it means nothing else can
        // start using the file between here and the unlink.
        if (old && flock(fd, LOCK_EX | LOCK_NB) == 0) {
            unlink(fsPath);
            flock(fd, LOCK_UN);
        }
        close(fd);
    }
}

void PVSweepAbandonedSnapshotsNow(void)
{
    PVSweepAbandonedSnapshots();
}

@implementation PVPDFSnapshot

// Why the snapshot stays a named file on disk, rather than an unlinked
// descriptor passed to helpers.
//
// An anonymous already-unlinked file would be crash-clean -- nothing survives
// the process -- and that was tried. It does not work here, for a reason worth
// recording so it is not tried again: on Darwin, opening /dev/fd/N is a dup(),
// not a fresh open. Every helper handed the same descriptor would share ONE
// file offset with every other helper and with this process. Two render lanes
// and the thumbnail source seeking concurrently through one shared offset is
// not a tidiness question, it is torn reads of the document, and Quartz gives
// no assurance it reads by pread rather than lseek. Verified experimentally,
// not assumed: seeking a /dev/fd/N descriptor moves the original's offset.
//
// So the file keeps a name, each helper does its own independent open(), and
// the residue of a crash is one file in NSTemporaryDirectory, which the system
// reaps. That is the smaller of the two prices.
- (id)initWithSourceURL:(NSURL *)url error:(NSError **)outError
{
    self = [super init];
    if (!self) return nil;
    _lockFD = -1;

    // Once per process, and here rather than at launch: this is the moment a
    // temporary directory full of abandoned copies actually costs something,
    // and it keeps the sweep out of the path of an app that never opens a file.
    static dispatch_once_t sweepOnce;
    dispatch_once(&sweepOnce, ^{ PVSweepAbandonedSnapshots(); });

    NSString *pattern = [NSTemporaryDirectory()
        stringByAppendingPathComponent:@"" PV_SNAPSHOT_PREFIX "XXXXXX"];
    char *tmp = strdup([pattern fileSystemRepresentation]);
    void *buffer = NULL;
    int input = -1, output = -1, saved = 0;
    long long copied = 0;
    struct stat before, after;
    struct statfs space;
    memset(&before, 0, sizeof(before));
    memset(&after, 0, sizeof(after));

    if (!tmp) { saved = ENOMEM; goto failed; }
    input = open([[[url path] stringByStandardizingPath] fileSystemRepresentation],
                 O_RDONLY);
    if (input < 0) { saved = errno; goto failed; }
    (void)fcntl(input, F_SETFD, FD_CLOEXEC);
    // The two failures are separated because only one of them sets errno.
    // fstat succeeding on something that is not a regular file leaves errno
    // holding whatever the last unrelated call left there -- or nothing at all,
    // which is an undefined read -- and the error the user is then shown is a
    // strerror() of that.
    if (fstat(input, &before) != 0) { saved = errno; goto failed; }
    if (!S_ISREG(before.st_mode))   { saved = EINVAL; goto failed; }
    // Bounded before a single byte is read, not discovered partway through.
    if (before.st_size < 0 || (long long)before.st_size > PV_MAX_PDF_BYTES) {
        saved = EFBIG;
        goto failed;
    }

    output = mkstemp(tmp);
    if (output < 0) { saved = errno; goto failed; }
    (void)fcntl(output, F_SETFD, FD_CLOEXEC);
    (void)fchmod(output, S_IRUSR | S_IWUSR);

    // Filling the volume is not Postview's failure to have alone: everything
    // else on the machine is writing to the same disk. Asked once, of the
    // volume the temporary file actually landed on rather than of the path it
    // was requested at.
    if (fstatfs(output, &space) == 0) {
        long long available = (long long)space.f_bavail * (long long)space.f_bsize;
        if (available < (long long)before.st_size + PV_SNAPSHOT_HEADROOM) {
            saved = ENOSPC;
            goto failed;
        }
    }

    buffer = malloc(128 * 1024);
    if (!buffer) { saved = ENOMEM; goto failed; }
    for (;;) {
        ssize_t got;
        do { got = read(input, buffer, 128 * 1024); }
        while (got < 0 && errno == EINTR);
        if (got < 0) { saved = errno; goto failed; }
        if (got == 0) break;

        // The bound again, this time against what is actually arriving. fstat
        // reported a size; a file being appended to, or one whose size the
        // filesystem misreports, can still deliver more than that, and the
        // ceiling has to hold against the bytes rather than against the claim.
        copied += (long long)got;
        if (copied > PV_MAX_PDF_BYTES) { saved = EFBIG; goto failed; }

        ssize_t offset = 0;
        while (offset < got) {
            ssize_t put;
            do { put = write(output, (char *)buffer + offset,
                             (size_t)(got - offset)); }
            while (put < 0 && errno == EINTR);
            if (put <= 0) { saved = errno ? errno : EIO; goto failed; }
            offset += put;
        }
    }
    if (fstat(input, &after) != 0) { saved = errno; goto failed; }
    // st_ctimespec as well as st_mtimespec: a rename, a permission change or a
    // truncation-and-rewrite that lands on the same mtime still moves ctime,
    // and any of them means the bytes just copied are not one coherent file.
    if (before.st_dev != after.st_dev || before.st_ino != after.st_ino ||
        before.st_size != after.st_size ||
        before.st_mtimespec.tv_sec != after.st_mtimespec.tv_sec ||
        before.st_mtimespec.tv_nsec != after.st_mtimespec.tv_nsec ||
        before.st_ctimespec.tv_sec != after.st_ctimespec.tv_sec ||
        before.st_ctimespec.tv_nsec != after.st_ctimespec.tv_nsec) {
        saved = EBUSY;
        goto failed;
    }
    // What was actually copied, against what was promised. The size comparison
    // above comes from two fstats of the same descriptor; this one is the only
    // check that the copy loop itself moved the whole file.
    if (copied != (long long)after.st_size) { saved = EBUSY; goto failed; }

    // No fsync.
    //
    // It was here, and it bought nothing: this file is deleted when the
    // document closes, so it has no durability requirement whatsoever -- there
    // is no state worth surviving a power cut in a copy whose entire purpose is
    // to be thrown away. What it cost was a blocking flush of up to two
    // gigabytes on the thread opening the document, and, on a network volume
    // that went away mid-open, an indefinite hang in the one call that cannot
    // be given a deadline.

    // -[NSFileManager stringWithFileSystemRepresentation:length:] is the one
    // that exists; the NSString spelling of it does not, and resolved to a
    // guessed `id` return at compile time.
    _path = [[[NSFileManager defaultManager]
        stringWithFileSystemRepresentation:tmp length:strlen(tmp)] copy];
    if (!_path) { saved = ENOMEM; goto failed; }

    // The claim on this file, held until -dealloc. Shared rather than
    // exclusive, so several snapshots of the same document -- which cannot
    // happen, but the lock should not be the thing that decides that -- and,
    // more usefully, so the sweeper's LOCK_EX is the only thing that ever
    // conflicts. A failure to take it is not fatal: the worst case is that a
    // future sweep reclaims this file an hour early, and refusing to open the
    // document over it would be far worse.
    _lockFD = dup(output);
    if (_lockFD >= 0) {
        (void)fcntl(_lockFD, F_SETFD, FD_CLOEXEC);
        if (flock(_lockFD, LOCK_SH | LOCK_NB) != 0) {
            close(_lockFD);
            _lockFD = -1;
        }
    }

    free(buffer);
    close(input);
    close(output);
    free(tmp);
    return self;

failed:
    if (buffer) free(buffer);
    if (input >= 0) close(input);
    if (output >= 0) close(output);
    if (tmp) {
        unlink(tmp);
        free(tmp);
    }
    if (outError) {
        NSString *reason;
        if (saved == EFBIG) {
            reason = @"It is larger than the two gigabytes Postview will copy "
                     @"before opening a document.";
        } else if (saved == ENOSPC) {
            reason = @"There is not enough free space to copy it safely.";
        } else {
            reason = [NSString stringWithFormat:
                @"The source changed or became unreadable (%s).",
                strerror(saved ? saved : EIO)];
        }
        *outError = PVError(8, @"This PDF could not be copied safely.", reason);
    }
    [self release];
    return nil;
}

- (NSString *)path { return _path; }

- (void)dealloc
{
    if (_path) unlink([_path fileSystemRepresentation]);
    // After the unlink, so the lock is held across it and a sweep running in
    // another process cannot get between the two.
    if (_lockFD >= 0) { flock(_lockFD, LOCK_UN); close(_lockFD); _lockFD = -1; }
    [_path release];
    [super dealloc];
}

@end

// A number no other shared-memory segment in this process will use.
//
// Process-global rather than per-source, which is what lets the NAME drop the
// source pointer: the pointer was there to disambiguate two sources using the
// same counter, and it cost 12 of the 31 characters available. Atomic because
// two render lanes reach this concurrently.
static uint64_t PVNextSharedMemoryToken(void)
{
    static volatile int64_t counter;
    return (uint64_t)__sync_add_and_fetch(&counter, 1);
}

typedef struct {
    void *address;
    size_t length;
} PVSharedBitmap;

static void PVReleaseSharedBitmap(void *info, const void *data, size_t size)
{
    PVSharedBitmap *bitmap = (PVSharedBitmap *)info;
    if (bitmap) {
        if (bitmap->address && bitmap->length)
            munmap(bitmap->address, bitmap->length);
        free(bitmap);
    }
}

static BOOL PVWriteExact(int fd, const void *bytes, size_t length)
{
    size_t offset = 0;
    while (offset < length) {
        ssize_t count = write(fd, (const char *)bytes + offset, length - offset);
        if (count < 0 && errno == EINTR) continue;
        if (count <= 0) return NO;
        offset += (size_t)count;
    }
    return YES;
}

// Read exactly `length` bytes, or give up at `deadline`.
//
// `outTimedOut` separates the two ways this returns NO, and they are not the
// same failure: a deadline means the helper is wedged inside Quartz and is
// worth another try with a fresh process, while EOF means it is gone. The
// caller has to be able to tell them apart -- see PVRenderFailure.
static BOOL PVReadExactUntil(int fd, void *bytes, size_t length, double deadline,
                             BOOL *outTimedOut)
{
    size_t offset = 0;
    if (outTimedOut) *outTimedOut = NO;
    while (offset < length) {
        double left = deadline - PVMonotonicSeconds();
        if (!(left > 0)) { if (outTimedOut) *outTimedOut = YES; return NO; }
        int milliseconds = (left > 60.0) ? 60000 : (int)ceil(left * 1000.0);
        if (milliseconds < 1) milliseconds = 1;
        struct pollfd item;
        item.fd = fd;
        item.events = POLLIN | POLLHUP | POLLERR;
        item.revents = 0;
        int ready;
        do { ready = poll(&item, 1, milliseconds); }
        while (ready < 0 && errno == EINTR);
        if (ready == 0) { if (outTimedOut) *outTimedOut = YES; return NO; }
        if (ready < 0 || (item.revents & (POLLERR | POLLNVAL))) return NO;

        ssize_t count = read(fd, (char *)bytes + offset, length - offset);
        if (count < 0 && errno == EINTR) continue;
        if (count <= 0) return NO;
        offset += (size_t)count;
    }
    return YES;
}

@interface PVPDFSource ()
- (NSString *)renderHelperPath;
- (BOOL)startHelperWithGeometry:(BOOL)wantGeometry
                          reply:(PVRenderOpenReply *)outReply
                        failure:(PVRenderFailure *)outFailure;
- (BOOL)ensureRenderHelper:(PVRenderFailure *)outFailure;
- (BOOL)readGeometryForPages:(NSUInteger)pages error:(NSError **)outError;
- (void)stopRenderHelper;
@end

@implementation PVPDFSource

- (id)initWithURL:(NSURL *)url error:(NSError **)outError
{
    return [self initWithURL:url geometryFrom:nil error:outError];
}

// The error a helper's open status means to the person who opened the file.
static NSError *PVOpenStatusError(int32_t status)
{
    switch (status) {
        case PVRenderOpenEncrypted:
            return PVError(3, @"This PDF is password protected.",
                @"Postview cannot unlock encrypted documents. Open it in Preview, "
                @"then re-save it without a password.");
        case PVRenderOpenNoPages:
            return PVError(4, @"This PDF has no pages.", nil);
        case PVRenderOpenTooManyPages:
            return PVError(5, @"This PDF is too large to open safely.",
                @"It has more pages than Postview can lay out within its fixed memory limit.");
        case PVRenderOpenOutOfMemory:
            return PVError(6, @"This PDF could not be opened.",
                @"There was not enough memory to lay out its pages.");
        default:
            return PVError(2, @"This file could not be opened.",
                @"It does not appear to be a readable PDF document.");
    }
}

- (id)initWithURL:(NSURL *)url geometryFrom:(PVPDFSource *)other error:(NSError **)outError
{
    self = [super init];
    if (!self) return nil;

    PVLiveAdjust("PVPDFSource", +1);
    // Before any path that can reach -dealloc. +alloc zeroes these, and zero is
    // a perfectly good file descriptor -- it is stdin -- so a -stopRenderHelper
    // reached from an early init failure would close the process's own standard
    // input and then close it again on the next source that failed to open.
    _helperIn  = -1;
    _helperOut = -1;
    _helperPid = 0;

    // The one external input, validated before anything is done with it, so an
    // invalid URL is always an ordinary open failure.
    if (![url isKindOfClass:[NSURL class]] || ![url isFileURL]) {
        if (outError) *outError = PVError(1, @"This file could not be opened.",
            @"Postview can open local PDF files only.");
        [self release];
        return nil;
    }
    _url = [url copy];
    _snapshot = other ? [other->_snapshot retain]
                      : [[PVPDFSnapshot alloc] initWithSourceURL:url error:outError];
    if (!_snapshot) {
        [self release];
        return nil;
    }

    // Geometry the caller already has, or geometry only the helper can measure.
    //
    // A source that must MEASURE starts its helper here rather than lazily on
    // the first render, and that is deliberate: an installation missing its
    // helper, or a document Quartz will not open, is a fact about the whole
    // document. Finding it out at open time produces one honest error; finding
    // it out on the first scroll produces a window full of blank pages and a
    // failure counter ticking down in silence.
    //
    // A source that COPIES geometry starts nothing here, and that is equally
    // deliberate. It has no question to ask, and asking anyway would mean the
    // second render lane and the thumbnail source each spawning a process and
    // waiting for it to parse the whole PDF -- on the main thread, inside
    // -[PVWindowController initWithSource:url:], before the window appears. On
    // the twelve-core machine that is the only one to get a second lane, that
    // turned one parse at open into three. Whatever those sources need, they
    // find out on their first render, which is where they used to find it out.
    BOOL copyGeometry = (other && other != self && [other pageCount] > 0);
    if (copyGeometry) {
        NSUInteger count = [other pageCount];
        if (count > PV_MAX_PDF_PAGES ||
            count > (NSUInteger)(SIZE_MAX / sizeof(CGSize))) {
            if (outError) *outError = PVOpenStatusError(PVRenderOpenTooManyPages);
            [self release];
            return nil;
        }
        _pageCount = count;
        _sizes = (CGSize *)calloc(_pageCount, sizeof(CGSize));
        if (!_sizes) {
            if (outError) *outError = PVOpenStatusError(PVRenderOpenOutOfMemory);
            [self release];
            return nil;
        }
        NSUInteger i;
        _maxSize = CGSizeMake(1, 1);
        for (i = 0; i < _pageCount; i++) {
            CGSize s = PVUsablePageSize([other pointSizeOfPage:i]);
            _sizes[i] = s;
            if (s.width  > _maxSize.width)  _maxSize.width  = s.width;
            if (s.height > _maxSize.height) _maxSize.height = s.height;
        }
        return self;
    }

    PVRenderOpenReply reply;
    PVRenderFailure failure = PVRenderFailureNone;
    if (![self startHelperWithGeometry:YES reply:&reply failure:&failure]) {
        if (outError) {
            *outError = (failure == PVRenderFailureHelperUnavailable)
                ? PVError(9, @"Postview cannot render documents.",
                          @"Its renderer is missing from the application bundle. "
                          @"Reinstall Postview.")
                : PVError(2, @"This file could not be opened.",
                          @"Its renderer stopped before it could describe the document.");
        }
        [self release];
        return nil;
    }
    if (reply.status != PVRenderOpenOK) {
        if (outError) *outError = PVOpenStatusError(reply.status);
        [self release];
        return nil;
    }
    // Believed only after it has been bounded. PV_MAX_PDF_PAGES is enforced in
    // the helper too; a parent that took the number on trust would be trusting
    // the one process in this design that is expected to misbehave.
    if (reply.pageCount == 0 || reply.pageCount > PV_MAX_PDF_PAGES ||
        reply.pageCount > (uint64_t)(SIZE_MAX / sizeof(CGSize))) {
        if (outError) *outError = PVOpenStatusError(PVRenderOpenTooManyPages);
        [self release];
        return nil;
    }
    _pageCount = (NSUInteger)reply.pageCount;

    _sizes = (CGSize *)calloc(_pageCount, sizeof(CGSize));
    if (!_sizes) {
        // Every other failure path here sets outError. This one did not, and
        // -[PVDocument readFromURL:] then returned NO with *outError still nil,
        // which is the one thing AppKit's open path is not prepared for.
        if (outError) *outError = PVOpenStatusError(PVRenderOpenOutOfMemory);
        [self release];
        return nil;
    }

    if (reply.geometryCount != (uint32_t)_pageCount ||
        ![self readGeometryForPages:_pageCount error:outError]) {
        if (outError && !*outError)
            *outError = PVError(7, @"This PDF could not be opened.",
                @"Its page geometry could not be read safely.");
        [self release];
        return nil;
    }
    return self;
}

// Read the per-page records the helper promised, under one deadline for the lot.
//
// One deadline rather than one per record: a hundred thousand records at the
// per-record deadline would be a hundred thousand chances to be slow, which is
// not a bound on anything. The helper is killed and the open fails if the whole
// description does not arrive in time.
- (BOOL)readGeometryForPages:(NSUInteger)pages error:(NSError **)outError
{
    if (_helperOut < 0) return NO;
    double deadline = PVMonotonicSeconds() + PV_OPEN_DEADLINE_SECONDS;
    _maxSize = CGSizeMake(1, 1);

    NSUInteger i;
    for (i = 0; i < pages; i++) {
        PVRenderPageGeometry record;
        BOOL timedOut = NO;
        if (!PVReadExactUntil(_helperOut, &record, sizeof(record), deadline,
                              &timedOut)) {
            [self stopRenderHelper];
            return NO;
        }
        CGSize s;
        if (!isfinite(record.width) || !isfinite(record.height)) {
            s = CGSizeMake(612, 792);
        } else if (record.rotation == 90 || record.rotation == 270) {
            s = CGSizeMake((CGFloat)record.height, (CGFloat)record.width);
        } else {
            s = CGSizeMake((CGFloat)record.width, (CGFloat)record.height);
        }
        // Clamp pathological geometry so layout math stays sane, without
        // inventing a shape the document does not have: see PVUsablePageSize.
        s = PVUsablePageSize(s);
        _sizes[i] = s;
        if (s.width  > _maxSize.width)  _maxSize.width  = s.width;
        if (s.height > _maxSize.height) _maxSize.height = s.height;
    }
    return YES;
}

- (void)dealloc
{
    PVLiveAdjust("PVPDFSource", -1);
    [self stopRenderHelper];
    if (_sizes) free(_sizes);
    [_snapshot release];
    [_url release];
    [super dealloc];
}

- (PVPDFSource *)newLaneSource
{
    // [self class], not PVPDFSource: a subclass that instruments rendering --
    // pvtest has one -- must see the second lane's renders too, or the
    // instrumentation silently covers half the work on a two-lane machine.
    return [[[self class] alloc] initWithURL:_url geometryFrom:self error:NULL];
}

- (NSUInteger)pageCount            { return _pageCount; }
- (CGSize)maxPointSize             { return _maxSize; }

- (CGSize)pointSizeOfPage:(NSUInteger)index
{
    if (index >= _pageCount) return CGSizeMake(612, 792);
    return _sizes[index];
}

- (NSString *)renderHelperPath
{
    NSString *directory = [[[NSBundle mainBundle] executablePath]
        stringByDeletingLastPathComponent];
    return [directory stringByAppendingPathComponent:@"PostviewRenderHelper"];
}

// Kill the helper and reap it. Safe from any thread, and safe from -dealloc:
// no run loop is spun and no Objective-C object is involved.
//
// The pipes are closed first. A helper blocked in read() sees EOF and exits on
// its own; SIGKILL then covers the one that is wedged inside Quartz, which is
// the entire reason this process exists. waitpid without WNOHANG is bounded
// because SIGKILL is uncatchable -- the child cannot decline it, and it is
// already dead or dying by the time this waits.
- (void)stopRenderHelper
{
    if (_helperIn  >= 0) { close(_helperIn);  _helperIn  = -1; }
    if (_helperOut >= 0) { close(_helperOut); _helperOut = -1; }

    if (_helperPid > 0) {
        (void)kill(_helperPid, SIGKILL);
        int status = 0;
        pid_t reaped;
        do { reaped = waitpid(_helperPid, &status, 0); }
        while (reaped < 0 && errno == EINTR);
        _helperPid = 0;
    }
    _helperRenders = 0;
}

- (BOOL)startHelperWithGeometry:(BOOL)wantGeometry
                          reply:(PVRenderOpenReply *)outReply
                        failure:(PVRenderFailure *)outFailure
{
    PVRenderFailure ignored;
    if (!outFailure) outFailure = &ignored;
    *outFailure = PVRenderFailureNone;
    [self stopRenderHelper];

    NSString *helperPath = [self renderHelperPath];
    if (![[NSFileManager defaultManager] isExecutableFileAtPath:helperPath]) {
        _helperUnavailable = YES;
        *outFailure = PVRenderFailureHelperUnavailable;
        return NO;
    }

    // A helper that dies mid-command turns the next write into SIGPIPE, which
    // would take the whole viewer down for the one failure this design exists
    // to contain. Ignored process-wide; the write returns EPIPE instead and the
    // render is reported as failed.
    static dispatch_once_t ignoreBrokenPipeOnce;
    dispatch_once(&ignoreBrokenPipeOnce, ^{ signal(SIGPIPE, SIG_IGN); });

    int toHelper[2]   = { -1, -1 };
    int fromHelper[2] = { -1, -1 };
    posix_spawn_file_actions_t actions;
    posix_spawnattr_t attr;
    BOOL actionsReady = NO, attrReady = NO;
    pid_t pid = 0;

    if (pipe(toHelper) != 0)   goto failed;
    if (pipe(fromHelper) != 0) goto failed;

    if (posix_spawn_file_actions_init(&actions) != 0) goto failed;
    actionsReady = YES;

    // Only the two pipe ends the helper needs, plus a null stderr. Everything
    // else this process holds -- the snapshot, the state store, the window
    // server connection -- is closed in the child by POSIX_SPAWN_CLOEXEC_DEFAULT
    // below, so a helper that is killed cannot be holding anything open.
    if (posix_spawn_file_actions_adddup2(&actions, toHelper[0], STDIN_FILENO) != 0 ||
        posix_spawn_file_actions_adddup2(&actions, fromHelper[1], STDOUT_FILENO) != 0 ||
        posix_spawn_file_actions_addopen(&actions, STDERR_FILENO,
                                         "/dev/null", O_WRONLY, 0) != 0)
        goto failed;

    if (posix_spawnattr_init(&attr) != 0) goto failed;
    attrReady = YES;
    // Checked, not discarded. Without POSIX_SPAWN_CLOEXEC_DEFAULT the child
    // inherits every descriptor this process holds -- the snapshot, the state
    // store's lock, the window server connection -- and a helper killed while
    // wedged would take those open descriptors with it into the grave. A
    // silently ignored failure here is a containment property silently lost.
    if (posix_spawnattr_setflags(&attr, POSIX_SPAWN_CLOEXEC_DEFAULT) != 0)
        goto failed;

    {
        char *argv[4];
        argv[0] = (char *)[helperPath fileSystemRepresentation];
        argv[1] = (char *)[[_snapshot path] fileSystemRepresentation];
        argv[2] = (char *)(wantGeometry ? PV_HELPER_MODE_META
                                        : PV_HELPER_MODE_RENDER);
        argv[3] = NULL;
        int rc = posix_spawn(&pid, argv[0], &actions, &attr, argv, NULL);
        if (rc != 0) { pid = 0; goto failed; }
    }

    // Not cleared afterwards: nothing below this point can reach `failed`, so a
    // second destroy is unreachable rather than guarded against. Assigning the
    // flags here would be a store the analyser correctly reports as dead.
    posix_spawnattr_destroy(&attr);
    posix_spawn_file_actions_destroy(&actions);

    // The child's ends, closed in the parent: without this the parent holds the
    // write end of its own read pipe and never sees EOF when the helper dies.
    close(toHelper[0]);   toHelper[0] = -1;
    close(fromHelper[1]); fromHelper[1] = -1;

    (void)fcntl(toHelper[1],  F_SETFD, FD_CLOEXEC);
    (void)fcntl(fromHelper[0], F_SETFD, FD_CLOEXEC);

    _helperPid = pid;
    _helperIn  = toHelper[1];
    _helperOut = fromHelper[0];
    _helperRenders = 0;

    {
        // The open reply, before this helper is considered started at all. It
        // arrives under its own deadline for the same reason every other
        // exchange does: the helper may be parsing something that never ends.
        PVRenderOpenReply reply;
        memset(&reply, 0, sizeof(reply));
        BOOL timedOut = NO;
        double deadline = PVMonotonicSeconds() + PV_OPEN_DEADLINE_SECONDS;
        BOOL got = PVReadExactUntil(_helperOut, &reply, sizeof(reply),
                                    deadline, &timedOut);
        if (!got || reply.magic != PV_RENDER_PROTOCOL_MAGIC ||
            reply.version != PV_RENDER_PROTOCOL_VERSION) {
            [self stopRenderHelper];
            *outFailure = !got && timedOut ? PVRenderFailureTimeout
                        : !got             ? PVRenderFailureHelperUnavailable
                                           : PVRenderFailureProtocol;
            return NO;
        }
        if (outReply) *outReply = reply;
    }
    return YES;

failed:
    if (attrReady)    posix_spawnattr_destroy(&attr);
    if (actionsReady) posix_spawn_file_actions_destroy(&actions);
    if (toHelper[0]   >= 0) close(toHelper[0]);
    if (toHelper[1]   >= 0) close(toHelper[1]);
    if (fromHelper[0] >= 0) close(fromHelper[0]);
    if (fromHelper[1] >= 0) close(fromHelper[1]);
    if (pid > 0) {
        (void)kill(pid, SIGKILL);
        int status = 0;
        pid_t reaped;
        do { reaped = waitpid(pid, &status, 0); }
        while (reaped < 0 && errno == EINTR);
    }
    // A resource failure, not a broken installation. Everything reaching this
    // label is a pipe that could not be made, a spawn_file_actions that could
    // not be initialised, or a posix_spawn that could not fork -- all of them
    // things a machine briefly out of descriptors or process slots does, and
    // all of them worth trying again. The helper being MISSING is answered far
    // above, before any of this is attempted, and that one is permanent.
    *outFailure = PVRenderFailureTransientResource;
    return NO;
}

// A helper ready to take a render command, starting one if the last was killed
// or retired.
- (BOOL)ensureRenderHelper:(PVRenderFailure *)outFailure
{
    if (_helperPid > 0 && _helperIn >= 0 && _helperOut >= 0) return YES;
    if (_helperUnavailable) {
        *outFailure = PVRenderFailureHelperUnavailable;
        return NO;
    }

    PVRenderOpenReply reply;
    memset(&reply, 0, sizeof(reply));
    if (![self startHelperWithGeometry:NO reply:&reply failure:outFailure])
        return NO;
    // The replacement has to be looking at the same document the geometry was
    // measured from. It is the same snapshot bytes, so a disagreement here
    // means the snapshot is gone or damaged, and no page will render again.
    if (reply.status != PVRenderOpenOK ||
        reply.pageCount != (uint64_t)_pageCount) {
        [self stopRenderHelper];
        *outFailure = PVRenderFailureProtocol;
        return NO;
    }
    return YES;
}

// What the helper's reply status means about whether this is worth retrying.
static PVRenderFailure PVFailureForReplyStatus(int32_t status)
{
    switch (status) {
        // The renderer declined this page: a page object the document would not
        // hand back, or a bitmap context Quartz refused to build over a buffer
        // it had already been told the shape of. Deterministic.
        case EINVAL:  return PVRenderFailureInvalidPage;
        case EPROTO:  return PVRenderFailureProtocol;
        // Everything else is an errno from shm_open or mmap inside the helper:
        // a resource that was not available at that instant.
        default:      return PVRenderFailureTransientResource;
    }
}

- (CGImageRef)createImageForPage:(NSUInteger)index pixelSize:(CGSize)px
{
    return [self createImageForPage:index pixelSize:px interactive:NO failure:NULL];
}

- (CGImageRef)createImageForPage:(NSUInteger)index
                       pixelSize:(CGSize)px
                         failure:(PVRenderFailure *)failure
{
    return [self createImageForPage:index pixelSize:px interactive:NO
                            failure:failure];
}

- (CGImageRef)createImageForPage:(NSUInteger)index
                       pixelSize:(CGSize)px
                     interactive:(BOOL)interactive
                         failure:(PVRenderFailure *)failure
{
    PVRenderFailure ignored;
    if (!failure) failure = &ignored;
    *failure = PVRenderFailureNone;

    if (index >= _pageCount) { *failure = PVRenderFailureInvalidPage; return NULL; }
    CGSize use = PVClampPixelSize(px);
    if (!(use.width >= 1) || !(use.height >= 1)) {
        *failure = PVRenderFailureInvalidPage;
        return NULL;
    }

    size_t width = (size_t)use.width;
    size_t height = (size_t)use.height;
    if (width > (SIZE_MAX - 63) / 4) { *failure = PVRenderFailureInvalidPage; return NULL; }
    size_t bytesPerRow = (width * 4 + 63) & ~(size_t)63;
    if (height > SIZE_MAX / bytesPerRow) { *failure = PVRenderFailureInvalidPage; return NULL; }
    size_t bytes = bytesPerRow * height;

    if (![self ensureRenderHelper:failure]) return NULL;

    // Both parts in hex and nothing else. A pid is at most 5 hex digits and the
    // token at most 16, so the longest name this can produce is
    // "/pv-" + 5 + "-" + 16 = 26 characters, comfortably inside
    // PV_SHM_NAME_MAX for the life of the process. See PV_SHM_NAME_MAX for what
    // went wrong when the name could outgrow it.
    char name[PV_RENDER_SHM_NAME_MAX + 1];
    int sharedFD = -1;
    unsigned attempt;
    for (attempt = 0; attempt < 16; attempt++) {
        _helperSequence = PVNextSharedMemoryToken();
        int written = snprintf(name, sizeof(name), "/pv-%x-%llx",
                               (unsigned)getpid(),
                               (unsigned long long)_helperSequence);
        // Stated rather than assumed. If the arithmetic above is ever wrong,
        // this fails one render loudly instead of failing every render for the
        // rest of the session in a way that looks like a blank document.
        if (written < 0 || (size_t)written >= sizeof(name)) {
            *failure = PVRenderFailureProtocol;
            return NULL;
        }
        sharedFD = shm_open(name, O_CREAT | O_EXCL | O_RDWR, 0600);
        if (sharedFD >= 0 || errno != EEXIST) break;
    }
    if (sharedFD < 0) { *failure = PVRenderFailureTransientResource; return NULL; }
    (void)fcntl(sharedFD, F_SETFD, FD_CLOEXEC);
    if (ftruncate(sharedFD, (off_t)bytes) != 0) {
        close(sharedFD); shm_unlink(name);
        *failure = PVRenderFailureTransientResource;
        return NULL;
    }

    // PROT_READ, and no memset.
    //
    // Both halves of that are the same decision. The viewer used to map the
    // segment writable and zero every byte of it before handing the name over,
    // which did two unwanted things: it made this process touch every page of a
    // ~28 MB mapping, so a deferred backing-store failure raised SIGBUS HERE --
    // in the process the helper exists to keep alive -- and it doubled the
    // memory traffic of every full-resolution render for bytes the helper
    // overwrites in full a moment later. PVRenderPDFPageToBuffer fills the whole
    // bitmap with white before it draws, and ftruncate guarantees the row
    // padding it does not reach is already zero.
    //
    // Read-only here also states the direction of the channel: the helper
    // writes pixels, the viewer reads them, and neither needs the other's
    // permission.
    void *map = mmap(NULL, bytes, PROT_READ, MAP_SHARED, sharedFD, 0);
    close(sharedFD);
    if (map == MAP_FAILED) {
        shm_unlink(name);
        *failure = PVRenderFailureTransientResource;
        return NULL;
    }

    PVResidentAdd(PVResidentRender, bytes);

    // Everything from here to the @finally is bracketed, because the resident
    // accounting and the mapping are both live across it. The old in-process
    // renderer had the same shape without the bracket: an Objective-C exception
    // raised after PVResidentAdd unwound straight past the release, leaking the
    // buffer and leaving the render bucket permanently overstated -- which then
    // shrank every later render's budget for the rest of the session.
    //
    // `map` is handed to the returned image on the success path, so ownership of
    // it moves to `handed` rather than being released here.
    CGImageRef image = NULL;
    BOOL handed = NO;
    BOOL retire = NO;
    @try {
        PVRenderCommand command;
        memset(&command, 0, sizeof(command));
        command.magic = PV_RENDER_PROTOCOL_MAGIC;
        command.version = PV_RENDER_PROTOCOL_VERSION;
        command.sequence = _helperSequence;
        command.page = index;
        command.width = (uint32_t)width;
        command.height = (uint32_t)height;
        command.priority = interactive ? PVRenderPriorityInteractive
                                       : PVRenderPriorityBackground;
        command.bytesPerRow = bytesPerRow;
        command.naturalWidth = _sizes[index].width;
        command.naturalHeight = _sizes[index].height;
        strlcpy(command.sharedMemoryName, name, sizeof(command.sharedMemoryName));

        BOOL wrote = PVWriteExact(_helperIn, &command, sizeof(command));
        PVRenderReply reply;
        memset(&reply, 0, sizeof(reply));
        BOOL timedOut = NO;
        double deadline = PVMonotonicSeconds() +
                          PVRenderDeadlineSeconds(width, height);
        BOOL readReply = wrote && PVReadExactUntil(_helperOut, &reply,
                                                   sizeof(reply), deadline,
                                                   &timedOut);
        BOOL wellFormed = (readReply &&
                           reply.magic == PV_RENDER_PROTOCOL_MAGIC &&
                           reply.version == PV_RENDER_PROTOCOL_VERSION &&
                           reply.sequence == command.sequence);
        BOOL succeeded = (wellFormed && reply.status == 0);

        if (!succeeded) {
            // A missed deadline, a protocol error and a dead helper are the same
            // situation: this helper can no longer be trusted to be at a message
            // boundary. Kill and reap it here; the next render starts a fresh
            // one. The kill happens before the mapping is dropped, so a helper
            // that was still writing is gone before the memory is.
            //
            // What differs between them is what the LAYER ABOVE should do, and
            // that is the whole point of reporting a reason rather than NULL: a
            // page Quartz will never draw has to stop being asked for, and a
            // page that lost a race with a killed helper has to be asked again.
            *failure = !wrote      ? PVRenderFailureProtocol
                     : timedOut    ? PVRenderFailureTimeout
                     : !readReply  ? PVRenderFailureProtocol
                     : !wellFormed ? PVRenderFailureProtocol
                                   : PVFailureForReplyStatus(reply.status);
            [self stopRenderHelper];
        } else {
            PVSharedBitmap *bitmap =
                (PVSharedBitmap *)calloc(1, sizeof(PVSharedBitmap));
            if (bitmap) {
                bitmap->address = map;
                bitmap->length = bytes;
                CGDataProviderRef provider = CGDataProviderCreateWithData(
                    bitmap, map, bytes, PVReleaseSharedBitmap);
                if (!provider) {
                    free(bitmap);
                } else {
                    // From here the provider owns the mapping: releasing it
                    // runs PVReleaseSharedBitmap, so this frame must not.
                    handed = YES;
                    CGColorSpaceRef colorSpace = CGColorSpaceCreateDeviceRGB();
                    if (colorSpace) {
                        image = CGImageCreate(width, height, 8, 32, bytesPerRow,
                            colorSpace,
                            (CGBitmapInfo)kCGImageAlphaNoneSkipFirst |
                                kCGBitmapByteOrder32Host,
                            provider, NULL, true, kCGRenderingIntentDefault);
                        CGColorSpaceRelease(colorSpace);
                    }
                    CGDataProviderRelease(provider);
                }
            }
            if (!image) *failure = PVRenderFailureTransientResource;

            // Retire this helper if it has served enough, or has just served
            // something large enough that its parse cache is the thing worth
            // dropping. Decided here, between renders, so the replacement is
            // started by the next call rather than in the middle of this one.
            if (++_helperRenders >= PV_HELPER_MAX_RENDERS ||
                (uint64_t)bytes >= PV_HELPER_LARGE_FRAME)
                retire = YES;
        }
    }
    @finally {
        shm_unlink(name);
        PVResidentSub(PVResidentRender, bytes);
        if (!handed) munmap(map, bytes);
        if (retire) [self stopRenderHelper];
    }
    return image;
}

@end
