#import "PVPDFSource.h"
#import "PVRenderProtocol.h"
#include <sys/mman.h>
#include <sys/stat.h>
#include <sys/mount.h>
#include <sys/file.h>
#include <sys/socket.h>       // socketpair, sendmsg, SCM_RIGHTS
#include <sys/event.h>        // kqueue/NOTE_EXIT, for supervising the copier
#include <pthread.h>          // the detached reaper
#include <crt_externs.h>      // _NSGetEnviron, for handing a helper the environment
#include <sys/time.h>          // futimes, for the snapshot freshness guard
#include <sys/types.h>
#include <sys/wait.h>
#include <mach/mach_time.h>
#include <poll.h>
#include <fcntl.h>
#include <unistd.h>
#include <signal.h>
#include <spawn.h>
#include <errno.h>

// Deliberately no PVRenderCore.h and no <CoreGraphics/CGPDFDocument.h> use.
// This process does not open PDFs. See PVPDFSource.h.

// Renders one helper serves before it is retired and replaced.
//
// Quartz accumulates parsed content inside a CGPDFDocumentRef -- fonts, shading
// dictionaries, decoded images -- and never gives it back while the document is
// open. Measured at 183-242 MB of helper RSS against 34-40 MB in the viewer,
// which the soak gate could not see because it only ever looked at
// mach_task_self(). The process boundary that contains the faults is also the
// only lever that reclaims this: a fresh helper starts at nothing.
//
// Retired between renders, chosen by the viewer, so a recycle never turns into
// a failed page. A frame this large is worth recycling for on its own: it is a
// zoomed page whose parse cost is already paid and whose peak is the thing the
// budget cannot absorb twice.
#define PV_HELPER_MAX_RENDERS  128
#define PV_HELPER_LARGE_FRAME  (64ULL * 1024ULL * 1024ULL)

static NSError *PVError(NSInteger code, NSString *desc, NSString *reason)
{
    NSMutableDictionary *info = [NSMutableDictionary dictionary];
    if (desc)   [info setObject:desc   forKey:NSLocalizedDescriptionKey];
    if (reason) [info setObject:reason forKey:NSLocalizedRecoverySuggestionErrorKey];
    return [NSError errorWithDomain:@"PostviewErrorDomain" code:code userInfo:info];
}

// The largest page dimension the layout maths is willing to carry, in points.
// The PDF format's own limit is 14400 pt (200 in); anything past this is either
// corrupt or generated by something that did not read the spec.
#define PV_MAX_PAGE_POINTS  20000.0

// The longest name shm_open will accept, including the leading slash.
//
// This is PSHMNAMLEN, and it is 31 -- not PATH_MAX, and not the 96-byte field
// the protocol carries the name in. A longer name is refused outright with
// ENAMETOOLONG, so a naming scheme that grows with a counter stops working
// partway through a session rather than never working: measured, the previous
// scheme ("/postview-<pid>-<pointer>-<counter>") fitted for the first 99
// renders of a source and failed for every render after that, permanently,
// with the pages simply staying blank.
#define PV_SHM_NAME_MAX 31

// A page size layout can work with, preserving the page's shape.
//
// The two axes are clamped TOGETHER. They used to be clamped independently --
// each axis that was degenerate or past the ceiling was replaced with the
// corresponding US Letter dimension -- and for a page that failed on one axis
// only, that invents an aspect ratio the document does not have. A 25000 x 300
// pt banner became a 612 x 300 pt page: the renderer then fits the real crop
// box into that frame, which preserves aspect and so draws the banner as a
// 612 x 7 pt strip marooned in a 612 x 300 pt page, with the rest of the frame
// blank. The page is not distorted but it is the wrong page, and nothing
// anywhere says so.
//
// Scaling both axes by one factor keeps the shape, so the oversized page is
// simply presented smaller -- which is what a viewer should do with a page too
// large to lay out. Only a size that is degenerate in a way no scale can fix
// (non-finite, or not positive on both axes) falls back to US Letter, and that
// is a page with no geometry rather than one with too much.
static CGSize PVUsablePageSize(CGSize s)
{
    if (!isfinite(s.width) || !isfinite(s.height) ||
        !(s.width > 1) || !(s.height > 1))
        return CGSizeMake(612, 792);

    double k = 1.0;
    if (s.width  > PV_MAX_PAGE_POINTS) k = PV_MAX_PAGE_POINTS / (double)s.width;
    if (s.height > PV_MAX_PAGE_POINTS) {
        double kh = PV_MAX_PAGE_POINTS / (double)s.height;
        if (kh < k) k = kh;
    }
    if (k >= 1.0) return s;

    CGSize out = CGSizeMake((CGFloat)((double)s.width * k),
                            (CGFloat)((double)s.height * k));
    // The scale cannot make either axis degenerate -- both were above 1 and the
    // factor is the ratio of the ceiling to the larger of them -- but the floor
    // is stated rather than reasoned about, because everything downstream
    // divides by these.
    if (!(out.width  > 1) || !isfinite(out.width))  out.width  = 1;
    if (!(out.height > 1) || !isfinite(out.height)) out.height = 1;
    return out;
}

// Whether a helper keeps its diagnostics: its stderr, and this process's
// environment.
//
// Both are suppressed in a shipping viewer, and for good reasons. A helper's
// stderr has nowhere useful to go, and an empty environment is one less thing a
// deliberately contained process inherits.
//
// Under test that same suppression threw away the only evidence the tests
// existed to collect. A sanitized helper writes its findings to stderr and
// takes its configuration from the environment, so a helper spawned with
// neither reports nothing and is configured by nothing -- which means every
// "address/thread sanitizer stress passed" only ever established that the
// PARENT passed. The renderer, the process that does the drawing and holds the
// shared mapping, was never actually being watched.
//
// Opt-in through the environment, so that no shipping build can take this path
// by accident and a developer can turn it on for a single run.
static BOOL PVHelperKeepsDiagnostics(void)
{
    static int cached = -1;
    if (cached < 0) {
        const char *value = getenv("PV_HELPER_DIAGNOSTICS");
        cached = (value && *value && strcmp(value, "0") != 0) ? 1 : 0;
    }
    return cached ? YES : NO;
}

// The environment a helper is spawned with: none at all, unless diagnostics are
// wanted. posix_spawn takes NULL to mean an empty environment, which is what a
// contained renderer should have and exactly the wrong thing for a sanitized
// one.
static char *const *PVHelperEnvironment(void)
{
    return PVHelperKeepsDiagnostics() ? (char *const *)*_NSGetEnviron() : NULL;
}

// Where the render helper lives: beside this executable, whatever this
// executable is. A C function because the copier needs it before any
// PVPDFSource exists.
static NSString *PVRenderHelperPath(void)
{
    NSString *directory = [[[NSBundle mainBundle] executablePath]
        stringByDeletingLastPathComponent];
    return [directory stringByAppendingPathComponent:@"PostviewRenderHelper"];
}

static void *PVReaperThread(void *context)
{
    pid_t pid = (pid_t)(intptr_t)context;
    int status = 0;
    pid_t reaped;
    do { reaped = waitpid(pid, &status, 0); }
    while (reaped < 0 && errno == EINTR);
    return NULL;
}

// Reap a child without ever blocking this thread on one that will not die.
//
// waitpid(..., 0) on a process that has been SIGKILLed is normally instant, and
// for every child this program starts on a good day it is. It is not instant
// for a child wedged in an uninterruptible filesystem call: SIGKILL is recorded
// and delivered when the call returns, which for a dead SMB mount can be
// minutes, or never. A blocking wait there hangs the viewer on exactly the
// fault the child process exists to contain -- the containment holds right up
// until the tidying up throws it away.
//
// So the wait is bounded, and what cannot be waited for here is waited for
// somewhere that does not matter. The zombie is reaped whenever the kernel lets
// go of it; nothing is leaked and nothing is blocked.
static void PVReapEventually(pid_t pid)
{
    if (pid <= 0) return;

    int attempt;
    for (attempt = 0; attempt < 50; attempt++) {
        int status = 0;
        pid_t reaped = waitpid(pid, &status, WNOHANG);
        if (reaped == pid) return;
        // ECHILD means it is already reaped and there is nothing owed.
        if (reaped < 0 && errno != EINTR) return;
        usleep(2000);
    }

    pthread_t thread;
    pthread_attr_t attr;
    if (pthread_attr_init(&attr) != 0) return;
    (void)pthread_attr_setdetachstate(&attr, PTHREAD_CREATE_DETACHED);
    (void)pthread_create(&thread, &attr, PVReaperThread, (void *)(intptr_t)pid);
    pthread_attr_destroy(&attr);
}

// Watch a copier until it finishes, stalls, or the world ends.
//
// Two things are being waited for at once and they need different mechanisms.
// The copier EXITING is an event, and NOTE_EXIT delivers it the instant it
// happens, so an ordinary local copy costs nothing in latency. The copier
// STALLING is the absence of an event, and the only honest evidence for it is
// the snapshot not growing -- which is why the file itself is the progress
// report and there is no second channel to keep in step with the first.
//
// Returns 0 when the copier exited successfully, or the errno to fail with.
static int PVSuperviseCopier(pid_t pid, int output)
{
    int queue = kqueue();
    if (queue < 0) {
        // Nothing to watch with. Failing closed is right: this is a machine out
        // of descriptors, the copy is about to fail anyway, and the alternative
        // -- waiting on an unwatched child -- is the unbounded wait this whole
        // function exists to prevent.
        int saved = errno;
        (void)kill(pid, SIGKILL);
        PVReapEventually(pid);
        return saved ? saved : ENOMEM;
    }

    struct kevent change;
    EV_SET(&change, (uintptr_t)pid, EVFILT_PROC, EV_ADD | EV_ENABLE,
           NOTE_EXIT, 0, NULL);
    if (kevent(queue, &change, 1, NULL, 0, NULL) != 0) {
        // The usual reason is that the child is already gone, which is not a
        // failure -- the status is waiting to be collected.
        if (errno != ESRCH) {
            int saved = errno;
            close(queue);
            (void)kill(pid, SIGKILL);
            PVReapEventually(pid);
            return saved;
        }
    }

    off_t grown = 0;
    double moved = PVMonotonicSeconds();
    int result = 0;

    for (;;) {
        struct kevent event;
        struct timespec wait;
        wait.tv_sec = PV_COPY_POLL_SECONDS;
        wait.tv_nsec = 0;

        int n = kevent(queue, NULL, 0, &event, 1, &wait);
        if (n < 0 && errno == EINTR) continue;
        if (n < 0) { result = errno; (void)kill(pid, SIGKILL); break; }

        if (n > 0) {
            // Exited. waitpid cannot block here: the child is already a zombie,
            // which is the whole reason NOTE_EXIT was worth waiting on.
            int status = 0;
            pid_t reaped;
            do { reaped = waitpid(pid, &status, 0); }
            while (reaped < 0 && errno == EINTR);
            close(queue);
            if (reaped != pid) return EIO;
            // A copier that died of a signal did not decide anything; only one
            // that exited chose its status, and that status is an errno.
            if (!WIFEXITED(status)) return EIO;
            return WEXITSTATUS(status);
        }

        // A tick with no exit. The snapshot is the evidence.
        struct stat info;
        if (fstat(output, &info) == 0 && info.st_size > grown) {
            grown = info.st_size;
            moved = PVMonotonicSeconds();
            continue;
        }
        if (PVMonotonicSeconds() - moved > PV_COPY_STALL_SECONDS) {
            result = ETIMEDOUT;
            (void)kill(pid, SIGKILL);
            break;
        }
    }

    close(queue);
    // Whatever it was doing, it is not being waited for on this thread.
    PVReapEventually(pid);
    return result ? result : EIO;
}

// Copy `url` into `output` in a process that can be killed. Returns 0, or the
// errno to fail the document open with.
static int PVCopyThroughCopier(NSURL *url, int output)
{
    NSString *helperPath = PVRenderHelperPath();
    if (![[NSFileManager defaultManager] isExecutableFileAtPath:helperPath])
        return ENOENT;

    NSString *source = [[url path] stringByStandardizingPath];
    if (![source length]) return EINVAL;

    posix_spawn_file_actions_t actions;
    posix_spawnattr_t attr;
    BOOL actionsReady = NO, attrReady = NO;
    pid_t pid = 0;
    int saved = 0;

    if (posix_spawn_file_actions_init(&actions) != 0) return errno ? errno : ENOMEM;
    actionsReady = YES;

    // The snapshot at stdout, and nothing else of this process's. The copier
    // reads a path it is given and writes one descriptor it is handed; it has
    // no use for anything else the viewer holds and must not be able to take
    // any of it into a wedged state.
    if (posix_spawn_file_actions_adddup2(&actions, output, PV_COPY_OUTPUT_FD) != 0 ||
        posix_spawn_file_actions_addopen(&actions, STDIN_FILENO,
                                         "/dev/null", O_RDONLY, 0) != 0) {
        saved = ENOMEM;
        goto done;
    }
    if (!PVHelperKeepsDiagnostics() &&
        posix_spawn_file_actions_addopen(&actions, STDERR_FILENO,
                                         "/dev/null", O_WRONLY, 0) != 0) {
        saved = ENOMEM;
        goto done;
    }

    if (posix_spawnattr_init(&attr) != 0) { saved = ENOMEM; goto done; }
    attrReady = YES;
    if (posix_spawnattr_setflags(&attr, POSIX_SPAWN_CLOEXEC_DEFAULT) != 0) {
        saved = ENOMEM;
        goto done;
    }

    {
        char *argv[4];
        argv[0] = (char *)[helperPath fileSystemRepresentation];
        argv[1] = (char *)[source fileSystemRepresentation];
        argv[2] = (char *)PV_HELPER_MODE_COPY;
        argv[3] = NULL;
        int rc = posix_spawn(&pid, argv[0], &actions, &attr, argv,
                             PVHelperEnvironment());
        if (rc != 0) { pid = 0; saved = rc; goto done; }
    }

done:
    if (attrReady)    posix_spawnattr_destroy(&attr);
    if (actionsReady) posix_spawn_file_actions_destroy(&actions);
    if (saved != 0)   return saved;

    return PVSuperviseCopier(pid, output);
}

@interface PVPDFSnapshot : NSObject {
    NSString *_path;
    // Held open for the snapshot's whole life. It is never read or written
    // through: it exists to carry the shared advisory lock, and to be the
    // thing -refresh touches, so that neither operation can ever land on a
    // file that merely has the same name. See PVSweepAbandonedSnapshots.
    int       _fd;
    // Whether _fd currently carries the lock. Separate from _fd because a
    // descriptor without a lock is still worth keeping -- it is what lets
    // -refresh push the mtime forward and try for the lock again.
    BOOL      _locked;
    // What file this snapshot IS. Recorded at creation so that a reopen by
    // path can prove it found the same inode and not a successor.
    dev_t     _dev;
    ino_t     _ino;
}
- (id)initWithSourceURL:(NSURL *)url error:(NSError **)outError;
- (NSString *)path;
- (void)refresh;
@end

// The prefix every snapshot's name begins with. One definition, because a
// sweeper that disagreed with the maker about the name would either delete
// nothing or delete something else.
#define PV_SNAPSHOT_PREFIX "Postview-PDF-"

// Snapshots left behind by processes that are gone.
//
// A snapshot is unlinked in -dealloc, which covers every ordinary exit and none
// of the others: kill -9, a crash, a power cut. Measured on the development
// machine after a day of testing -- 41 abandoned files, ~100 MB. The system
// does eventually reap its temporary directory, but "eventually" is not a
// bound, and a reader who crashes twice a week accumulates.
//
// Whether a file is abandoned is asked twice, not guessed, and a file is
// deleted only if both answers agree.
//
// The lock is the exact question. Every live snapshot holds a shared advisory
// lock on its own file, so a file that will accept an exclusive lock is a file
// no live snapshot is using.
//
// The age is the independent one, and it is a real guard rather than the
// courtesy to older builds it was first written as. -[PVPDFSnapshot refresh]
// pushes a live snapshot's mtime forward every time a helper starts, so a
// document being read is never `old` no matter what happened to its lock. That
// matters because the lock CAN fail to be taken -- a process out of descriptors
// at exactly the wrong moment -- and when it did, this test was the only thing
// standing between a live document and its snapshot being deleted out from
// under it. Two guards that fail independently are the point; either one alone
// was not enough.
#define PV_SNAPSHOT_STALE_SECONDS (3600.0)

static void PVSweepAbandonedSnapshots(void)
{
    NSString *directory = NSTemporaryDirectory();
    if (![directory length]) return;

    NSFileManager *fm = [NSFileManager defaultManager];
    NSArray *names = [fm contentsOfDirectoryAtPath:directory error:NULL];
    NSString *prefix = [NSString stringWithUTF8String:PV_SNAPSHOT_PREFIX];
    NSUInteger i, n = [names count];
    for (i = 0; i < n; i++) {
        NSString *name = [names objectAtIndex:i];
        if (![name isKindOfClass:[NSString class]]) continue;
        if (![name hasPrefix:prefix]) continue;

        NSString *path = [directory stringByAppendingPathComponent:name];
        const char *fsPath = [path fileSystemRepresentation];
        int fd = open(fsPath, O_RDONLY);
        if (fd < 0) continue;

        struct stat info;
        BOOL old = (fstat(fd, &info) == 0 && S_ISREG(info.st_mode) &&
                    (time(NULL) - info.st_mtimespec.tv_sec) >
                        (time_t)PV_SNAPSHOT_STALE_SECONDS);
        // The exclusive lock is the question and the answer both: taking it
        // proves nothing else holds it, and holding it means nothing else can
        // start using the file between here and the unlink.
        if (old && flock(fd, LOCK_EX | LOCK_NB) == 0) {
            unlink(fsPath);
            flock(fd, LOCK_UN);
        }
        close(fd);
    }
}

void PVSweepAbandonedSnapshotsNow(void)
{
    PVSweepAbandonedSnapshots();
}

@implementation PVPDFSnapshot

// Why the snapshot stays a named file on disk, rather than an unlinked
// descriptor passed to helpers.
//
// An anonymous already-unlinked file would be crash-clean -- nothing survives
// the process -- and that was tried. It does not work here, for a reason worth
// recording so it is not tried again: on Darwin, opening /dev/fd/N is a dup(),
// not a fresh open. Every helper handed the same descriptor would share ONE
// file offset with every other helper and with this process. Two render lanes
// and the thumbnail source seeking concurrently through one shared offset is
// not a tidiness question, it is torn reads of the document, and Quartz gives
// no assurance it reads by pread rather than lseek. Verified experimentally,
// not assumed: seeking a /dev/fd/N descriptor moves the original's offset.
//
// So the file keeps a name, each helper does its own independent open(), and
// the residue of a crash is one file in NSTemporaryDirectory, which the system
// reaps. That is the smaller of the two prices.
- (id)initWithSourceURL:(NSURL *)url error:(NSError **)outError
{
    self = [super init];
    if (!self) return nil;
    _fd = -1;
    _locked = NO;

    // Once per process, and here rather than at launch: this is the moment a
    // temporary directory full of abandoned copies actually costs something,
    // and it keeps the sweep out of the path of an app that never opens a file.
    static dispatch_once_t sweepOnce;
    dispatch_once(&sweepOnce, ^{ PVSweepAbandonedSnapshots(); });

    NSString *pattern = [NSTemporaryDirectory()
        stringByAppendingPathComponent:@"" PV_SNAPSHOT_PREFIX "XXXXXX"];
    char *tmp = strdup([pattern fileSystemRepresentation]);
    int output = -1, saved = 0;

    if (!tmp) { saved = ENOMEM; goto failed; }

    // The destination first, and it is the only file this process opens.
    //
    // Everything that touches the SOURCE now happens in a copier subprocess.
    // Nothing below this point can block on a volume that has gone away: a
    // local mkstemp cannot hang, and the copy itself is watched from the
    // outside and killed if it stops moving. See PV_HELPER_MODE_COPY.
    output = mkstemp(tmp);
    if (output < 0) { saved = errno; goto failed; }
    (void)fcntl(output, F_SETFD, FD_CLOEXEC);
    (void)fchmod(output, S_IRUSR | S_IWUSR);

    // Every bound that used to be enforced inline -- the size ceiling, the
    // free-space headroom, the regular-file test, and the before/after identity
    // comparison that proves the bytes are one coherent file -- is enforced by
    // the copier, on the far side of the process boundary. What comes back is
    // the errno it decided on, or ETIMEDOUT if it had to be killed.
    saved = PVCopyThroughCopier(url, output);
    if (saved != 0) goto failed;

    // No fsync.
    //
    // It was here, and it bought nothing: this file is deleted when the
    // document closes, so it has no durability requirement whatsoever -- there
    // is no state worth surviving a power cut in a copy whose entire purpose is
    // to be thrown away. What it cost was a blocking flush of up to two
    // gigabytes on the thread opening the document, and, on a network volume
    // that went away mid-open, an indefinite hang in the one call that cannot
    // be given a deadline.

    // -[NSFileManager stringWithFileSystemRepresentation:length:] is the one
    // that exists; the NSString spelling of it does not, and resolved to a
    // guessed `id` return at compile time.
    _path = [[[NSFileManager defaultManager]
        stringWithFileSystemRepresentation:tmp length:strlen(tmp)] copy];
    if (!_path) { saved = ENOMEM; goto failed; }

    // What this file is, before anything else can claim the name.
    {
        struct stat made;
        if (fstat(output, &made) != 0) { saved = errno; goto failed; }
        _dev = made.st_dev;
        _ino = made.st_ino;
    }

    // The claim on this file, held until -dealloc. Shared rather than
    // exclusive, so several snapshots of the same document -- which cannot
    // happen, but the lock should not be the thing that decides that -- and,
    // more usefully, so the sweeper's LOCK_EX is the only thing that ever
    // conflicts.
    //
    // A failure to take it still does not refuse the document: that was the
    // right call and it stands. What has changed is that the failure is no
    // longer permanent and no longer unguarded -- the descriptor is kept
    // regardless, and -refresh retries the lock and pushes the mtime forward
    // every time a helper starts. See -refresh for why one guard was not
    // enough.
    _fd = dup(output);
    if (_fd >= 0) {
        (void)fcntl(_fd, F_SETFD, FD_CLOEXEC);
        _locked = (flock(_fd, LOCK_SH | LOCK_NB) == 0);
    }

    close(output);
    free(tmp);
    return self;

failed:
    if (output >= 0) close(output);
    // The partial snapshot goes with the failure. A copier that was killed
    // leaves a half-written file behind, and leaving it for the sweeper would
    // mean an hour of a truncated document sitting in the temporary directory.
    if (tmp) {
        unlink(tmp);
        free(tmp);
    }
    if (outError) {
        NSString *reason;
        if (saved == EFBIG) {
            reason = @"It is larger than the two gigabytes Postview will copy "
                     @"before opening a document.";
        } else if (saved == ENOSPC) {
            reason = @"There is not enough free space to copy it safely.";
        } else if (saved == ETIMEDOUT) {
            // The one failure that is about the VOLUME rather than the file,
            // and the one a reader can actually act on: the disk or share the
            // document is on has stopped answering.
            reason = @"The disk or network share it is on stopped responding. "
                     @"Check that the volume is still connected, then try "
                     @"again.";
        } else if (saved == ENOENT) {
            reason = @"It could not be found, or Postview's renderer is "
                     @"missing from the application bundle.";
        } else {
            reason = [NSString stringWithFormat:
                @"The source changed or became unreadable (%s).",
                strerror(saved ? saved : EIO)];
        }
        *outError = PVError(8, @"This PDF could not be copied safely.", reason);
    }
    [self release];
    return nil;
}

- (NSString *)path { return _path; }

// Say, twice over, that this snapshot is still in use.
//
// PVSweepAbandonedSnapshots deletes a file only when it is BOTH older than
// PV_SNAPSHOT_STALE_SECONDS and willing to give up an exclusive lock. Those
// read like two independent guards, and they were written as two, but only one
// of them was ever actually maintained: the lock was taken once at creation and
// a failure to take it was ignored for the rest of the document's life. An
// unlocked snapshot was therefore protected by its mtime alone, and after an
// hour a sweep in another Postview would delete a file this process was still
// reading.
//
// The shape of that fault is the reason it is worth this much code. The
// document goes on rendering perfectly out of the helper that already has it
// open, and stops the moment that helper is recycled -- so it is minutes of
// entirely normal behaviour, then permanent blankness, with the cause an hour
// in the past and in a different process.
//
// So both guards are now really held, and re-held on every helper start:
//   * the mtime is pushed forward, so a snapshot in use is never `old`;
//   * a lock that was never taken, or was lost, is taken now.
// Neither can refuse to open a document, and neither is load-bearing alone.
- (void)refresh
{
    if (!_path) return;

    // No descriptor at all: creation could not dup one. Reopen by name, and
    // prove it is the same inode -- if a sweep has already taken this file the
    // name may belong to something else entirely.
    if (_fd < 0) {
        int fd = open([_path fileSystemRepresentation], O_RDONLY);
        if (fd >= 0) {
            struct stat found;
            if (fstat(fd, &found) == 0 &&
                found.st_dev == _dev && found.st_ino == _ino) {
                (void)fcntl(fd, F_SETFD, FD_CLOEXEC);
                _fd = fd;
            } else {
                close(fd);
            }
        }
    }
    if (_fd < 0) return;

    if (!_locked) _locked = (flock(_fd, LOCK_SH | LOCK_NB) == 0);

    // NULL is "now". By descriptor, so it cannot touch a file that merely has
    // the same name as ours.
    (void)futimes(_fd, NULL);
}

- (void)dealloc
{
    if (_path) unlink([_path fileSystemRepresentation]);
    // After the unlink, so the lock is held across it and a sweep running in
    // another process cannot get between the two.
    if (_fd >= 0) {
        if (_locked) flock(_fd, LOCK_UN);
        close(_fd);
        _fd = -1;
        _locked = NO;
    }
    [_path release];
    [super dealloc];
}

@end

// A number no other shared-memory segment in this process will use.
//
// Process-global rather than per-source, which is what lets the NAME drop the
// source pointer: the pointer was there to disambiguate two sources using the
// same counter, and it cost 12 of the 31 characters available. Atomic because
// two render lanes reach this concurrently.
static uint64_t PVNextSharedMemoryToken(void)
{
    static volatile int64_t counter;
    return (uint64_t)__sync_add_and_fetch(&counter, 1);
}

typedef struct {
    void *address;
    size_t length;
} PVSharedBitmap;

static void PVReleaseSharedBitmap(void *info, const void *data, size_t size)
{
    PVSharedBitmap *bitmap = (PVSharedBitmap *)info;
    if (bitmap) {
        if (bitmap->address && bitmap->length)
            munmap(bitmap->address, bitmap->length);
        free(bitmap);
    }
}

// One command, with the bitmap's descriptor attached.
//
// The descriptor rides in an SCM_RIGHTS control message on the same sendmsg as
// the command it belongs to, so the two cannot be separated, reordered or
// mismatched: a helper that has a command has the buffer that command refers
// to, or it has neither.
//
// A short send is treated as a failure rather than resumed. The protocol is
// strictly one command in flight at a time and the struct is a couple of
// hundred bytes against a socket buffer measured in kilobytes, so a partial
// write here does not mean "busy", it means something is wrong with the
// channel -- and the caller's answer to that, killing the helper and starting
// a fresh one, is the right answer to all of it.
static BOOL PVSendCommandWithDescriptor(int socket,
                                        const PVRenderCommand *command,
                                        int descriptor)
{
    struct iovec item;
    item.iov_base = (void *)command;
    item.iov_len  = sizeof(*command);

    // Aligned as a cmsghdr, and sized by a constant.
    //
    // Two separate hazards, both invisible until they are not. The union gives
    // the storage cmsghdr alignment, which CMSG_FIRSTHDR needs and a bare char
    // array does not promise. The odd-looking length is because CMSG_SPACE is
    // NOT a constant expression on the 10.9 SDK -- __DARWIN_ALIGN32 casts
    // through a size_t -- so using it to size an array quietly produced a
    // variable-length array inside a union, which is a clang extension rather
    // than C. sizeof(struct cmsghdr) + sizeof(int) + 32 is a genuine constant
    // and is comfortably above CMSG_SPACE(sizeof(int)), which cannot exceed
    // sizeof(struct cmsghdr) + 3 + sizeof(int) + 3.
    union {
        struct cmsghdr align;
        char           bytes[sizeof(struct cmsghdr) + sizeof(int) + 32];
    } control;
    memset(&control, 0, sizeof(control));

    // Stated rather than trusted to the arithmetic above.
    if (sizeof(control.bytes) < CMSG_SPACE(sizeof(int))) return NO;

    struct msghdr message;
    memset(&message, 0, sizeof(message));
    message.msg_iov        = &item;
    message.msg_iovlen     = 1;
    message.msg_control    = control.bytes;
    message.msg_controllen = CMSG_SPACE(sizeof(int));

    struct cmsghdr *header = CMSG_FIRSTHDR(&message);
    if (!header) return NO;
    header->cmsg_level = SOL_SOCKET;
    header->cmsg_type  = SCM_RIGHTS;
    header->cmsg_len   = CMSG_LEN(sizeof(int));
    memcpy(CMSG_DATA(header), &descriptor, sizeof(descriptor));

    ssize_t sent;
    do { sent = sendmsg(socket, &message, 0); }
    while (sent < 0 && errno == EINTR);
    return (sent == (ssize_t)sizeof(*command));
}

// Read exactly `length` bytes, or give up at `deadline`.
//
// `outTimedOut` separates the two ways this returns NO, and they are not the
// same failure: a deadline means the helper is wedged inside Quartz and is
// worth another try with a fresh process, while EOF means it is gone. The
// caller has to be able to tell them apart -- see PVRenderFailure.
static BOOL PVReadExactUntil(int fd, void *bytes, size_t length, double deadline,
                             BOOL *outTimedOut)
{
    size_t offset = 0;
    if (outTimedOut) *outTimedOut = NO;
    while (offset < length) {
        double left = deadline - PVMonotonicSeconds();
        if (!(left > 0)) { if (outTimedOut) *outTimedOut = YES; return NO; }
        int milliseconds = (left > 60.0) ? 60000 : (int)ceil(left * 1000.0);
        if (milliseconds < 1) milliseconds = 1;
        struct pollfd item;
        item.fd = fd;
        item.events = POLLIN | POLLHUP | POLLERR;
        item.revents = 0;
        // A signal sends this back to the top of the loop rather than round an
        // inner one, so `left` is recomputed from the absolute deadline. The
        // inner retry passed the ORIGINAL timeout to poll again, which quietly
        // extended the deadline by up to one full interval every time a signal
        // arrived -- and the deadline is the only thing bounding a helper that
        // has stopped answering.
        int ready = poll(&item, 1, milliseconds);
        if (ready < 0 && errno == EINTR) continue;
        if (ready == 0) { if (outTimedOut) *outTimedOut = YES; return NO; }
        if (ready < 0 || (item.revents & (POLLERR | POLLNVAL))) return NO;

        ssize_t count = read(fd, (char *)bytes + offset, length - offset);
        if (count < 0 && errno == EINTR) continue;
        if (count <= 0) return NO;
        offset += (size_t)count;
    }
    return YES;
}

@interface PVPDFSource ()
- (NSString *)renderHelperPath;
- (BOOL)startHelperWithGeometry:(BOOL)wantGeometry
                          reply:(PVRenderOpenReply *)outReply
                        failure:(PVRenderFailure *)outFailure;
- (BOOL)ensureRenderHelper:(PVRenderFailure *)outFailure;
- (BOOL)readGeometryForPages:(NSUInteger)pages error:(NSError **)outError;
- (void)stopRenderHelper;
@end

@implementation PVPDFSource

- (id)initWithURL:(NSURL *)url error:(NSError **)outError
{
    return [self initWithURL:url geometryFrom:nil error:outError];
}

// The error a helper's open status means to the person who opened the file.
static NSError *PVOpenStatusError(int32_t status)
{
    switch (status) {
        case PVRenderOpenEncrypted:
            return PVError(3, @"This PDF is password protected.",
                @"Postview cannot unlock encrypted documents. Open it in Preview, "
                @"then re-save it without a password.");
        case PVRenderOpenNoPages:
            return PVError(4, @"This PDF has no pages.", nil);
        case PVRenderOpenTooManyPages:
            return PVError(5, @"This PDF is too large to open safely.",
                @"It has more pages than Postview can lay out within its fixed memory limit.");
        case PVRenderOpenOutOfMemory:
            return PVError(6, @"This PDF could not be opened.",
                @"There was not enough memory to lay out its pages.");
        default:
            return PVError(2, @"This file could not be opened.",
                @"It does not appear to be a readable PDF document.");
    }
}

- (id)initWithURL:(NSURL *)url geometryFrom:(PVPDFSource *)other error:(NSError **)outError
{
    self = [super init];
    if (!self) return nil;

    PVLiveAdjust("PVPDFSource", +1);
    // Before any path that can reach -dealloc. +alloc zeroes these, and zero is
    // a perfectly good file descriptor -- it is stdin -- so a -stopRenderHelper
    // reached from an early init failure would close the process's own standard
    // input and then close it again on the next source that failed to open.
    _helperIn  = -1;
    _helperOut = -1;
    _helperPid = 0;

    // The one external input, validated before anything is done with it, so an
    // invalid URL is always an ordinary open failure.
    if (![url isKindOfClass:[NSURL class]] || ![url isFileURL]) {
        if (outError) *outError = PVError(1, @"This file could not be opened.",
            @"Postview can open local PDF files only.");
        [self release];
        return nil;
    }
    _url = [url copy];
    _snapshot = other ? [other->_snapshot retain]
                      : [[PVPDFSnapshot alloc] initWithSourceURL:url error:outError];
    if (!_snapshot) {
        [self release];
        return nil;
    }

    // Geometry the caller already has, or geometry only the helper can measure.
    //
    // A source that must MEASURE starts its helper here rather than lazily on
    // the first render, and that is deliberate: an installation missing its
    // helper, or a document Quartz will not open, is a fact about the whole
    // document. Finding it out at open time produces one honest error; finding
    // it out on the first scroll produces a window full of blank pages and a
    // failure counter ticking down in silence.
    //
    // A source that COPIES geometry starts nothing here, and that is equally
    // deliberate. It has no question to ask, and asking anyway would mean the
    // second render lane and the thumbnail source each spawning a process and
    // waiting for it to parse the whole PDF -- on the main thread, inside
    // -[PVWindowController initWithSource:url:], before the window appears. On
    // the twelve-core machine that is the only one to get a second lane, that
    // turned one parse at open into three. Whatever those sources need, they
    // find out on their first render, which is where they used to find it out.
    BOOL copyGeometry = (other && other != self && [other pageCount] > 0);
    if (copyGeometry) {
        NSUInteger count = [other pageCount];
        if (count > PV_MAX_PDF_PAGES ||
            count > (NSUInteger)(SIZE_MAX / sizeof(CGSize))) {
            if (outError) *outError = PVOpenStatusError(PVRenderOpenTooManyPages);
            [self release];
            return nil;
        }
        _pageCount = count;
        _sizes = (CGSize *)calloc(_pageCount, sizeof(CGSize));
        if (!_sizes) {
            if (outError) *outError = PVOpenStatusError(PVRenderOpenOutOfMemory);
            [self release];
            return nil;
        }
        NSUInteger i;
        _maxSize = CGSizeMake(1, 1);
        for (i = 0; i < _pageCount; i++) {
            CGSize s = PVUsablePageSize([other pointSizeOfPage:i]);
            _sizes[i] = s;
            if (s.width  > _maxSize.width)  _maxSize.width  = s.width;
            if (s.height > _maxSize.height) _maxSize.height = s.height;
        }
        return self;
    }

    PVRenderOpenReply reply;
    PVRenderFailure failure = PVRenderFailureNone;
    if (![self startHelperWithGeometry:YES reply:&reply failure:&failure]) {
        if (outError) {
            *outError = (failure == PVRenderFailureHelperUnavailable)
                ? PVError(9, @"Postview cannot render documents.",
                          @"Its renderer is missing from the application bundle. "
                          @"Reinstall Postview.")
                : PVError(2, @"This file could not be opened.",
                          @"Its renderer stopped before it could describe the document.");
        }
        [self release];
        return nil;
    }
    if (reply.status != PVRenderOpenOK) {
        if (outError) *outError = PVOpenStatusError(reply.status);
        [self release];
        return nil;
    }
    // Believed only after it has been bounded. PV_MAX_PDF_PAGES is enforced in
    // the helper too; a parent that took the number on trust would be trusting
    // the one process in this design that is expected to misbehave.
    if (reply.pageCount == 0 || reply.pageCount > PV_MAX_PDF_PAGES ||
        reply.pageCount > (uint64_t)(SIZE_MAX / sizeof(CGSize))) {
        if (outError) *outError = PVOpenStatusError(PVRenderOpenTooManyPages);
        [self release];
        return nil;
    }
    _pageCount = (NSUInteger)reply.pageCount;

    _sizes = (CGSize *)calloc(_pageCount, sizeof(CGSize));
    if (!_sizes) {
        // Every other failure path here sets outError. This one did not, and
        // -[PVDocument readFromURL:] then returned NO with *outError still nil,
        // which is the one thing AppKit's open path is not prepared for.
        if (outError) *outError = PVOpenStatusError(PVRenderOpenOutOfMemory);
        [self release];
        return nil;
    }

    if (reply.geometryCount != (uint32_t)_pageCount ||
        ![self readGeometryForPages:_pageCount error:outError]) {
        if (outError && !*outError)
            *outError = PVError(7, @"This PDF could not be opened.",
                @"Its page geometry could not be read safely.");
        [self release];
        return nil;
    }
    return self;
}

// Read the per-page records the helper promised, under one deadline for the lot.
//
// One deadline rather than one per record: a hundred thousand records at the
// per-record deadline would be a hundred thousand chances to be slow, which is
// not a bound on anything. The helper is killed and the open fails if the whole
// description does not arrive in time.
- (BOOL)readGeometryForPages:(NSUInteger)pages error:(NSError **)outError
{
    if (_helperOut < 0) return NO;
    double deadline = PVMonotonicSeconds() + PV_OPEN_DEADLINE_SECONDS;
    _maxSize = CGSizeMake(1, 1);

    NSUInteger i;
    for (i = 0; i < pages; i++) {
        PVRenderPageGeometry record;
        BOOL timedOut = NO;
        if (!PVReadExactUntil(_helperOut, &record, sizeof(record), deadline,
                              &timedOut)) {
            [self stopRenderHelper];
            return NO;
        }
        CGSize s;
        if (!isfinite(record.width) || !isfinite(record.height)) {
            s = CGSizeMake(612, 792);
        } else if (record.rotation == 90 || record.rotation == 270) {
            s = CGSizeMake((CGFloat)record.height, (CGFloat)record.width);
        } else {
            s = CGSizeMake((CGFloat)record.width, (CGFloat)record.height);
        }
        // Clamp pathological geometry so layout math stays sane, without
        // inventing a shape the document does not have: see PVUsablePageSize.
        s = PVUsablePageSize(s);
        _sizes[i] = s;
        if (s.width  > _maxSize.width)  _maxSize.width  = s.width;
        if (s.height > _maxSize.height) _maxSize.height = s.height;
    }
    return YES;
}

- (void)dealloc
{
    PVLiveAdjust("PVPDFSource", -1);
    [self stopRenderHelper];
    if (_sizes) free(_sizes);
    [_snapshot release];
    [_url release];
    [super dealloc];
}

- (PVPDFSource *)newLaneSource
{
    // [self class], not PVPDFSource: a subclass that instruments rendering --
    // pvtest has one -- must see the second lane's renders too, or the
    // instrumentation silently covers half the work on a two-lane machine.
    return [[[self class] alloc] initWithURL:_url geometryFrom:self error:NULL];
}

- (NSUInteger)pageCount            { return _pageCount; }
- (CGSize)maxPointSize             { return _maxSize; }

- (CGSize)pointSizeOfPage:(NSUInteger)index
{
    if (index >= _pageCount) return CGSizeMake(612, 792);
    return _sizes[index];
}

- (NSString *)renderHelperPath
{
    return PVRenderHelperPath();
}

// Kill the helper and reap it. Safe from any thread, and safe from -dealloc:
// no run loop is spun and no Objective-C object is involved.
//
// The pipes are closed first. A helper blocked in read() sees EOF and exits on
// its own; SIGKILL then covers the one that is wedged inside Quartz, which is
// the entire reason this process exists. waitpid without WNOHANG is bounded
// because SIGKILL is uncatchable -- the child cannot decline it, and it is
// already dead or dying by the time this waits.
- (void)stopRenderHelper
{
    if (_helperIn  >= 0) { close(_helperIn);  _helperIn  = -1; }
    if (_helperOut >= 0) { close(_helperOut); _helperOut = -1; }

    if (_helperPid > 0) {
        (void)kill(_helperPid, SIGKILL);
        // Bounded. A helper wedged inside Quartz takes the SIGKILL only when
        // the call it is stuck in returns, and blocking here for that would
        // hang the viewer on the exact fault the process boundary exists to
        // contain. See PVReapEventually.
        PVReapEventually(_helperPid);
        _helperPid = 0;
    }
    _helperRenders = 0;
}

- (BOOL)startHelperWithGeometry:(BOOL)wantGeometry
                          reply:(PVRenderOpenReply *)outReply
                        failure:(PVRenderFailure *)outFailure
{
    PVRenderFailure ignored;
    if (!outFailure) outFailure = &ignored;
    *outFailure = PVRenderFailureNone;
    [self stopRenderHelper];

    // Both sweep guards, re-asserted. Here rather than on a timer because this
    // is the moment that matters: a helper is about to open the snapshot by
    // name, so the name had better still be this file's.
    [_snapshot refresh];

    NSString *helperPath = [self renderHelperPath];
    if (![[NSFileManager defaultManager] isExecutableFileAtPath:helperPath]) {
        _helperUnavailable = YES;
        *outFailure = PVRenderFailureHelperUnavailable;
        return NO;
    }

    // A helper that dies mid-command turns the next write into SIGPIPE, which
    // would take the whole viewer down for the one failure this design exists
    // to contain. Ignored process-wide; the write returns EPIPE instead and the
    // render is reported as failed.
    static dispatch_once_t ignoreBrokenPipeOnce;
    dispatch_once(&ignoreBrokenPipeOnce, ^{ signal(SIGPIPE, SIG_IGN); });

    int toHelper[2]   = { -1, -1 };
    int fromHelper[2] = { -1, -1 };
    posix_spawn_file_actions_t actions;
    posix_spawnattr_t attr;
    BOOL actionsReady = NO, attrReady = NO;
    pid_t pid = 0;

    // Commands travel over a socketpair rather than a pipe, because each one
    // carries the bitmap's descriptor in an SCM_RIGHTS control message and only
    // an AF_UNIX socket can carry those. Replies are still an ordinary pipe:
    // nothing travels back but bytes.
    if (socketpair(AF_UNIX, SOCK_STREAM, 0, toHelper) != 0) goto failed;
    if (pipe(fromHelper) != 0) goto failed;

    if (posix_spawn_file_actions_init(&actions) != 0) goto failed;
    actionsReady = YES;

    // Only the two pipe ends the helper needs, plus a null stderr. Everything
    // else this process holds -- the snapshot, the state store, the window
    // server connection -- is closed in the child by POSIX_SPAWN_CLOEXEC_DEFAULT
    // below, so a helper that is killed cannot be holding anything open.
    if (posix_spawn_file_actions_adddup2(&actions, toHelper[0], STDIN_FILENO) != 0 ||
        posix_spawn_file_actions_adddup2(&actions, fromHelper[1], STDOUT_FILENO) != 0)
        goto failed;
    // stderr is discarded in a shipping viewer and kept under test. See
    // PVHelperKeepsDiagnostics: a sanitized helper that cannot write its
    // findings anywhere is a sanitized helper nobody is reading.
    if (!PVHelperKeepsDiagnostics() &&
        posix_spawn_file_actions_addopen(&actions, STDERR_FILENO,
                                         "/dev/null", O_WRONLY, 0) != 0)
        goto failed;

    if (posix_spawnattr_init(&attr) != 0) goto failed;
    attrReady = YES;
    // Checked, not discarded. Without POSIX_SPAWN_CLOEXEC_DEFAULT the child
    // inherits every descriptor this process holds -- the snapshot, the state
    // store's lock, the window server connection -- and a helper killed while
    // wedged would take those open descriptors with it into the grave. A
    // silently ignored failure here is a containment property silently lost.
    if (posix_spawnattr_setflags(&attr, POSIX_SPAWN_CLOEXEC_DEFAULT) != 0)
        goto failed;

    {
        char *argv[4];
        argv[0] = (char *)[helperPath fileSystemRepresentation];
        argv[1] = (char *)[[_snapshot path] fileSystemRepresentation];
        argv[2] = (char *)(wantGeometry ? PV_HELPER_MODE_META
                                        : PV_HELPER_MODE_RENDER);
        argv[3] = NULL;
        int rc = posix_spawn(&pid, argv[0], &actions, &attr, argv,
                             PVHelperEnvironment());
        if (rc != 0) { pid = 0; goto failed; }
    }

    // Not cleared afterwards: nothing below this point can reach `failed`, so a
    // second destroy is unreachable rather than guarded against. Assigning the
    // flags here would be a store the analyser correctly reports as dead.
    posix_spawnattr_destroy(&attr);
    posix_spawn_file_actions_destroy(&actions);

    // The child's ends, closed in the parent: without this the parent holds the
    // write end of its own read pipe and never sees EOF when the helper dies.
    close(toHelper[0]);   toHelper[0] = -1;
    close(fromHelper[1]); fromHelper[1] = -1;

    (void)fcntl(toHelper[1],  F_SETFD, FD_CLOEXEC);
    (void)fcntl(fromHelper[0], F_SETFD, FD_CLOEXEC);

    _helperPid = pid;
    _helperIn  = toHelper[1];
    _helperOut = fromHelper[0];
    _helperRenders = 0;

    {
        // The open reply, before this helper is considered started at all. It
        // arrives under its own deadline for the same reason every other
        // exchange does: the helper may be parsing something that never ends.
        PVRenderOpenReply reply;
        memset(&reply, 0, sizeof(reply));
        BOOL timedOut = NO;
        double deadline = PVMonotonicSeconds() + PV_OPEN_DEADLINE_SECONDS;
        BOOL got = PVReadExactUntil(_helperOut, &reply, sizeof(reply),
                                    deadline, &timedOut);
        if (!got || reply.magic != PV_RENDER_PROTOCOL_MAGIC ||
            reply.version != PV_RENDER_PROTOCOL_VERSION) {
            [self stopRenderHelper];
            // EOF here is NOT "the renderer is missing".
            //
            // Reaching this point means the executable was found, was
            // executable, and was spawned -- all of that is settled far above,
            // and that check is the only thing that can honestly report a
            // broken installation. What EOF means HERE is that a helper which
            // did start died before it answered: a crash in Quartz on the
            // document being opened, an out-of-memory kill, a signal. Calling
            // that PVRenderFailureHelperUnavailable put the viewer into its
            // permanent _helperUnavailable state and told the reader to
            // reinstall the application, for a fault in the file they had just
            // opened. It is a helper that cannot be trusted to be at a message
            // boundary, which is exactly PVRenderFailureProtocol, and the layer
            // above retries it under backoff instead of retiring the document.
            *outFailure = timedOut ? PVRenderFailureTimeout
                                   : PVRenderFailureProtocol;
            return NO;
        }
        if (outReply) *outReply = reply;
    }
    return YES;

failed:
    if (attrReady)    posix_spawnattr_destroy(&attr);
    if (actionsReady) posix_spawn_file_actions_destroy(&actions);
    if (toHelper[0]   >= 0) close(toHelper[0]);
    if (toHelper[1]   >= 0) close(toHelper[1]);
    if (fromHelper[0] >= 0) close(fromHelper[0]);
    if (fromHelper[1] >= 0) close(fromHelper[1]);
    if (pid > 0) {
        (void)kill(pid, SIGKILL);
        PVReapEventually(pid);
    }
    // A resource failure, not a broken installation. Everything reaching this
    // label is a pipe that could not be made, a spawn_file_actions that could
    // not be initialised, or a posix_spawn that could not fork -- all of them
    // things a machine briefly out of descriptors or process slots does, and
    // all of them worth trying again. The helper being MISSING is answered far
    // above, before any of this is attempted, and that one is permanent.
    *outFailure = PVRenderFailureTransientResource;
    return NO;
}

// A helper ready to take a render command, starting one if the last was killed
// or retired.
- (BOOL)ensureRenderHelper:(PVRenderFailure *)outFailure
{
    if (_helperPid > 0 && _helperIn >= 0 && _helperOut >= 0) return YES;
    if (_helperUnavailable) {
        *outFailure = PVRenderFailureHelperUnavailable;
        return NO;
    }

    PVRenderOpenReply reply;
    memset(&reply, 0, sizeof(reply));
    if (![self startHelperWithGeometry:NO reply:&reply failure:outFailure])
        return NO;
    // The replacement has to be looking at the same document the geometry was
    // measured from. It is the same snapshot bytes, so a disagreement here
    // means the snapshot is gone or damaged, and no page will render again.
    if (reply.status != PVRenderOpenOK ||
        reply.pageCount != (uint64_t)_pageCount) {
        [self stopRenderHelper];
        *outFailure = PVRenderFailureProtocol;
        return NO;
    }
    return YES;
}

// What the helper's reply status means about whether this is worth retrying.
static PVRenderFailure PVFailureForReplyStatus(int32_t status)
{
    switch (status) {
        // The renderer declined this page as asked for: no such page, or a
        // request whose shape contradicts itself. Deterministic.
        case EINVAL:  return PVRenderFailureInvalidPage;
        // Drawing refused: a non-finite transform out of the page's own boxes,
        // or an exception from inside CGContextDrawPDFPage. Also deterministic,
        // and carried separately from EINVAL only so that a malformed page and
        // a malformed request are distinguishable after the fact.
        case EILSEQ:  return PVRenderFailureInvalidPage;
        // The two ends disagreed about a structure they both computed.
        case EPROTO:  return PVRenderFailureProtocol;
        // Quartz could not get the memory to draw into. Stated rather than left
        // to the default, because this is the case the whole split exists for:
        // nothing is wrong with the page and it must be asked for again.
        case ENOMEM:  return PVRenderFailureTransientResource;
        // Everything else is an errno from shm_open or mmap inside the helper:
        // a resource that was not available at that instant.
        default:      return PVRenderFailureTransientResource;
    }
}

- (CGImageRef)createImageForPage:(NSUInteger)index pixelSize:(CGSize)px
{
    return [self createImageForPage:index pixelSize:px interactive:NO failure:NULL];
}

- (CGImageRef)createImageForPage:(NSUInteger)index
                       pixelSize:(CGSize)px
                         failure:(PVRenderFailure *)failure
{
    return [self createImageForPage:index pixelSize:px interactive:NO
                            failure:failure];
}

- (CGImageRef)createImageForPage:(NSUInteger)index
                       pixelSize:(CGSize)px
                     interactive:(BOOL)interactive
                         failure:(PVRenderFailure *)failure
{
    PVRenderFailure ignored;
    if (!failure) failure = &ignored;
    *failure = PVRenderFailureNone;

    if (index >= _pageCount) { *failure = PVRenderFailureInvalidPage; return NULL; }
    CGSize use = PVClampPixelSize(px);
    if (!(use.width >= 1) || !(use.height >= 1)) {
        *failure = PVRenderFailureInvalidPage;
        return NULL;
    }

    size_t width = (size_t)use.width;
    size_t height = (size_t)use.height;
    if (width > (SIZE_MAX - 63) / 4) { *failure = PVRenderFailureInvalidPage; return NULL; }
    size_t bytesPerRow = (width * 4 + 63) & ~(size_t)63;
    if (height > SIZE_MAX / bytesPerRow) { *failure = PVRenderFailureInvalidPage; return NULL; }
    size_t bytes = bytesPerRow * height;

    if (![self ensureRenderHelper:failure]) return NULL;

    // Both parts in hex and nothing else. A pid is at most 5 hex digits and the
    // token at most 16, so the longest name this can produce is
    // "/pv-" + 5 + "-" + 16 = 26 characters, comfortably inside
    // PV_SHM_NAME_MAX for the life of the process. See PV_SHM_NAME_MAX for what
    // went wrong when the name could outgrow it.
    char name[PV_SHM_NAME_MAX + 1];
    int sharedFD = -1;
    unsigned attempt;
    for (attempt = 0; attempt < 16; attempt++) {
        _helperSequence = PVNextSharedMemoryToken();
        int written = snprintf(name, sizeof(name), "/pv-%x-%llx",
                               (unsigned)getpid(),
                               (unsigned long long)_helperSequence);
        // Stated rather than assumed. If the arithmetic above is ever wrong,
        // this fails one render loudly instead of failing every render for the
        // rest of the session in a way that looks like a blank document.
        if (written < 0 || (size_t)written >= sizeof(name)) {
            *failure = PVRenderFailureProtocol;
            return NULL;
        }
        sharedFD = shm_open(name, O_CREAT | O_EXCL | O_RDWR, 0600);
        if (sharedFD >= 0 || errno != EEXIST) break;
    }
    if (sharedFD < 0) { *failure = PVRenderFailureTransientResource; return NULL; }
    (void)fcntl(sharedFD, F_SETFD, FD_CLOEXEC);
    if (ftruncate(sharedFD, (off_t)bytes) != 0) {
        close(sharedFD); shm_unlink(name);
        *failure = PVRenderFailureTransientResource;
        return NULL;
    }

    // The name is finished with the moment the object has a size, and it is
    // dropped here rather than after the render for exactly that reason. From
    // this point the object is reachable only through `sharedFD` and the
    // mappings made from it, so there is no window in which a SIGKILL to either
    // process can strand a named segment that nothing will ever unlink. See
    // PV_RENDER_COMMAND_CARRIES_FD.
    //
    // Unchecked: the name was created O_EXCL a few lines above and belongs to
    // this process, so the only way this fails is if it never existed, and the
    // shm_open above already proved otherwise.
    (void)shm_unlink(name);

    // PROT_READ, and no memset.
    //
    // Both halves of that are the same decision. The viewer used to map the
    // segment writable and zero every byte of it before handing the name over,
    // which did two unwanted things: it made this process touch every page of a
    // ~28 MB mapping, so a deferred backing-store failure raised SIGBUS HERE --
    // in the process the helper exists to keep alive -- and it doubled the
    // memory traffic of every full-resolution render for bytes the helper
    // overwrites in full a moment later. PVRenderPDFPageToBuffer fills the whole
    // bitmap with white before it draws, and ftruncate guarantees the row
    // padding it does not reach is already zero.
    //
    // Read-only here also states the direction of the channel: the helper
    // writes pixels, the viewer reads them, and neither needs the other's
    // permission.
    //
    // sharedFD stays open past this mapping: it is what gets sent to the
    // helper, and with the name already gone it is now the only way to name
    // this object at all.
    void *map = mmap(NULL, bytes, PROT_READ, MAP_SHARED, sharedFD, 0);
    if (map == MAP_FAILED) {
        close(sharedFD);
        *failure = PVRenderFailureTransientResource;
        return NULL;
    }

    PVResidentAdd(PVResidentRender, bytes);

    // Everything from here to the @finally is bracketed, because the resident
    // accounting and the mapping are both live across it. The old in-process
    // renderer had the same shape without the bracket: an Objective-C exception
    // raised after PVResidentAdd unwound straight past the release, leaking the
    // buffer and leaving the render bucket permanently overstated -- which then
    // shrank every later render's budget for the rest of the session.
    //
    // `map` is handed to the returned image on the success path, so ownership of
    // it moves to `handed` rather than being released here.
    CGImageRef image = NULL;
    BOOL handed = NO;
    BOOL retire = NO;
    @try {
        PVRenderCommand command;
        memset(&command, 0, sizeof(command));
        command.magic = PV_RENDER_PROTOCOL_MAGIC;
        command.version = PV_RENDER_PROTOCOL_VERSION;
        command.sequence = _helperSequence;
        command.page = index;
        command.width = (uint32_t)width;
        command.height = (uint32_t)height;
        command.priority = interactive ? PVRenderPriorityInteractive
                                       : PVRenderPriorityBackground;
        command.bytesPerRow = bytesPerRow;
        command.naturalWidth = _sizes[index].width;
        command.naturalHeight = _sizes[index].height;

        // The descriptor goes with the command and is closed the instant it has
        // been sent. The helper holds its own copy from here; this process
        // keeps only the read-only mapping it already made.
        BOOL wrote = PVSendCommandWithDescriptor(_helperIn, &command, sharedFD);
        close(sharedFD);
        sharedFD = -1;
        PVRenderReply reply;
        memset(&reply, 0, sizeof(reply));
        BOOL timedOut = NO;
        double deadline = PVMonotonicSeconds() +
                          PVRenderDeadlineSeconds(width, height);
        BOOL readReply = wrote && PVReadExactUntil(_helperOut, &reply,
                                                   sizeof(reply), deadline,
                                                   &timedOut);
        BOOL wellFormed = (readReply &&
                           reply.magic == PV_RENDER_PROTOCOL_MAGIC &&
                           reply.version == PV_RENDER_PROTOCOL_VERSION &&
                           reply.sequence == command.sequence);
        BOOL succeeded = (wellFormed && reply.status == 0);

        if (!succeeded) {
            // A missed deadline, a protocol error and a dead helper are the same
            // situation: this helper can no longer be trusted to be at a message
            // boundary. Kill and reap it here; the next render starts a fresh
            // one. The kill happens before the mapping is dropped, so a helper
            // that was still writing is gone before the memory is.
            //
            // What differs between them is what the LAYER ABOVE should do, and
            // that is the whole point of reporting a reason rather than NULL: a
            // page Quartz will never draw has to stop being asked for, and a
            // page that lost a race with a killed helper has to be asked again.
            *failure = !wrote      ? PVRenderFailureProtocol
                     : timedOut    ? PVRenderFailureTimeout
                     : !readReply  ? PVRenderFailureProtocol
                     : !wellFormed ? PVRenderFailureProtocol
                                   : PVFailureForReplyStatus(reply.status);
            [self stopRenderHelper];
        } else {
            PVSharedBitmap *bitmap =
                (PVSharedBitmap *)calloc(1, sizeof(PVSharedBitmap));
            if (bitmap) {
                bitmap->address = map;
                bitmap->length = bytes;
                CGDataProviderRef provider = CGDataProviderCreateWithData(
                    bitmap, map, bytes, PVReleaseSharedBitmap);
                if (!provider) {
                    free(bitmap);
                } else {
                    // From here the provider owns the mapping: releasing it
                    // runs PVReleaseSharedBitmap, so this frame must not.
                    handed = YES;
                    CGColorSpaceRef colorSpace = CGColorSpaceCreateDeviceRGB();
                    if (colorSpace) {
                        image = CGImageCreate(width, height, 8, 32, bytesPerRow,
                            colorSpace,
                            (CGBitmapInfo)kCGImageAlphaNoneSkipFirst |
                                kCGBitmapByteOrder32Host,
                            provider, NULL, true, kCGRenderingIntentDefault);
                        CGColorSpaceRelease(colorSpace);
                    }
                    CGDataProviderRelease(provider);
                }
            }
            if (!image) *failure = PVRenderFailureTransientResource;

            // Retire this helper if it has served enough, or has just served
            // something large enough that its parse cache is the thing worth
            // dropping. Decided here, between renders, so the replacement is
            // started by the next call rather than in the middle of this one.
            if (++_helperRenders >= PV_HELPER_MAX_RENDERS ||
                (uint64_t)bytes >= PV_HELPER_LARGE_FRAME)
                retire = YES;
        }
    }
    @finally {
        // No shm_unlink here any more: the name was dropped before the mapping
        // was made. Only the descriptor could still be open, and only if the
        // send never happened.
        if (sharedFD >= 0) close(sharedFD);
        PVResidentSub(PVResidentRender, bytes);
        if (!handed) munmap(map, bytes);
        if (retire) [self stopRenderHelper];
    }
    return image;
}

@end
